use std::fs::File;
use std::io::Read;
use toml::Value as TomlValue;

#[derive(Debug)]
pub struct Translations {
    pub map_settings: &'static str,
    pub map_scale: &'static str,
    pub map_opacity: &'static str,
    pub always_show_map: &'static str,
    pub hide_map_in_menus: &'static str,
    pub map_position: &'static str,
    pub center: &'static str,
    pub top_left: &'static str,
    pub top_right: &'static str,
    pub map_objects: &'static str,
    pub show_chests: &'static str,
    pub size: &'static str,
    pub show_portals: &'static str,
    pub show_shrines: &'static str,
    pub text_size: &'static str,
    pub monsters: &'static str,
    pub show_immunities: &'static str,
    pub normal_mobs: &'static str,
    pub minions: &'static str,
    pub champions: &'static str,
    pub uniques: &'static str,
    pub bosses: &'static str,
    pub lines_and_pathfinding: &'static str,
    pub show_waypoint_lines: &'static str,
    pub show_exit_lines: &'static str,
    pub show_quest_lines: &'static str,
    pub show_boss_lines: &'static str,
    pub missiles: &'static str,
    pub show_missiles: &'static str,
    pub fire: &'static str,
    pub cold: &'static str,
    pub poison: &'static str,
    pub lightning: &'static str,
    pub physical: &'static str,
    pub magic: &'static str,
    pub quit: &'static str,
    pub save_settings: &'static str,
    pub kashya: &'static str,
    pub akara: &'static str,
    pub deckardcain: &'static str,
    pub charsi: &'static str,
    pub warriv: &'static str,
    pub gheed: &'static str,
    pub lysander: &'static str,
    pub geglash: &'static str,
    pub greiz: &'static str,
    pub jerhyn: &'static str,
    pub drognan: &'static str,
    pub atma: &'static str,
    pub elzix: &'static str,
    pub meshif: &'static str,
    pub kaelan: &'static str,
    pub fara: &'static str,
    pub asheara: &'static str,
    pub natalya: &'static str,
    pub alkor: &'static str,
    pub ormus: &'static str,
    pub hratli: &'static str,
    pub halbu: &'static str,
    pub jamella: &'static str,
    pub tyrael: &'static str,
    pub larzuk: &'static str,
    pub malah: &'static str,
    pub drehya: &'static str,
    pub nihlathak: &'static str,
    pub qualkehk: &'static str,
    pub izual: &'static str,
    pub navi: &'static str,
    pub malachai: &'static str,
}

#[derive(Debug)]
pub enum Language {
    English,
    Spanish,
    German, 
    TraditionalChinese,
    Bogan,
    French,
    Italian,
    Korean,
    Dutch,
}

pub fn load_settings_language() -> Result<Language, Box<dyn std::error::Error>> {
    let mut file = File::open("settings.toml")?;
    let mut contents = String::new();
    file.read_to_string(&mut contents)?;
    let value: TomlValue = toml::from_str(&contents)?;
    
    let language_str = value.get("general").and_then(|v| v.get("language")).and_then(TomlValue::as_str).unwrap_or("en");
    let language = match language_str.to_lowercase().as_str() {
        "en" => Language::English,
        "es" => Language::Spanish,
        "de" => Language::German,
        "it" => Language::Italian,
        "fr" => Language::French,
        "ko" => Language::Korean,
        "nl" => Language::Dutch,
        "tw" => Language::TraditionalChinese,
        "bg" => Language::Bogan,
        _ => Language::English, // Default English if not found
    };
    
    Ok(language)
}

pub fn load_translations() -> Result<Translations, Box<dyn std::error::Error>> {
    let language = load_settings_language()?;
    let translations = get_translation(&language);
    Ok(translations)
}

pub fn get_translation(lang: &Language) -> Translations {
    match *lang {
        Language::English => Translations {
            map_settings: "Map settings",
            map_scale: "Map Scale",
            map_opacity: "Map Opacity",
            always_show_map: "Always Show Map",
            hide_map_in_menus: "Hide Map When Menus Are Showing",
            map_position: "Map Position",
            center: "Center",
            top_left: "Top Left",
            top_right: "Top Right",
            map_objects: "Map Objects",
            show_chests: "Show Chests",
            size: "Size",
            show_portals: "Show Portals",
            show_shrines: "Show Shrines",
            text_size: "Text Size",
            monsters: "Monsters",
            show_immunities: "Show Immunities",
            normal_mobs: "Normal Mobs",
            minions: "Minions",
            champions: "Champions",
            uniques: "Uniques",
            bosses: "Bosses",
            lines_and_pathfinding: "Lines/Pathfinding",
            show_waypoint_lines: "Show Waypoint Lines",
            show_exit_lines: "Show Exit Lines",
            show_quest_lines: "Show Quest Lines", 
            show_boss_lines: "Show Boss Lines",
            missiles: "Missiles",
            show_missiles: "Show Missiles",
            fire: "Fire",
            cold: "Cold",
            poison: "Poison",
            lightning: "Lightning",
            physical: "Physical",
            magic: "Magic",
            quit: "Quit",
            save_settings: "Save Settings",
            kashya: "Kashya",
            akara: "Akara",
            deckardcain: "Deckard Cain",
            charsi: "Charsi",
            warriv: "Warriv",
            gheed: "Gheed",
            lysander: "Lysander", 
            geglash: "Geglash",
            greiz: "Greiz",
            jerhyn: "Jerhyn",
            drognan: "Drognan",
            atma: "Atma",
            elzix: "Elzix",
            meshif: "Meshif",
            kaelan: "Kaelan",
            fara: "Fara",
            asheara: "Asheara",
            natalya: "Natalya",
            alkor: "Alkor",
            ormus: "Ormus",
            hratli: "Hratli",
            halbu: "Halbu",
            jamella: "Jamella",
            tyrael: "Tyrael",
            larzuk : "Larzuk",
            malah: "Malah",
            drehya: "Anya", //Anya
            nihlathak: "Nihlathak",
            qualkehk: "Qual-Kehk",
            izual: "Izual",
            navi: "Flavie", //Flavie
            malachai: "Hadriel", //Hadriel
        },
        Language::Spanish => Translations {
            map_settings: "Configuración del mapa",
            map_scale: "Escala del mapa",
            map_opacity: "Opacidad del mapa",
            always_show_map: "Mostrar siempre el mapa",
            hide_map_in_menus: "Ocultar mapa cuando los menús están abiertos",
            map_position: "Posición del mapa",
            center: "Centro",
            top_left: "Arriba a la izquierda",
            top_right: "Arriba a la derecha",
            map_objects: "Objetos del mapa",
            show_chests: "Mostrar cofres",
            size: "Tamaño",
            show_portals: "Mostrar portales",
            show_shrines: "Mostrar santuarios",
            text_size: "Tamaño del texto",
            monsters: "Monstruos",
            show_immunities: "Mostrar inmunidades",
            normal_mobs: "Mobs normales",
            minions: "Esbirros",
            champions: "Campeones",
            uniques: "Únicos",
            bosses: "Jefes",
            lines_and_pathfinding: "Líneas/Guía de camino",
            show_waypoint_lines: "Mostrar líneas de puntos de viaje",
            show_exit_lines: "Mostrar líneas de salida",
            show_quest_lines: "Mostrar líneas de misiones",
            show_boss_lines: "Mostrar líneas de jefes",
            missiles: "Misiles",
            show_missiles: "Mostrar misiles",
            fire: "Fuego",
            cold: "Frío",
            poison: "Veneno",
            lightning: "Rayo",
            physical: "Físico",
            magic: "Mágico",
            quit: "Salir",
            save_settings: "Guardar configuraciones",
            kashya: "Kashya",
            akara: "Akara",
            deckardcain: "Deckard Cain",
            charsi: "Charsi",
            warriv: "Warriv",
            gheed: "Gheed",
            lysander: "Lysander", 
            geglash: "Geglash",
            greiz: "Greiz",
            jerhyn: "Jerhyn",
            drognan: "Drognan",
            atma: "Atma",
            elzix: "Elzix",
            meshif: "Meshif",
            kaelan: "Kaelan",
            fara: "Fara",
            asheara: "Asheara",
            natalya: "Natalya",
            alkor: "Alkor",
            ormus: "Ormus",
            hratli: "Hratli",
            halbu: "Halbu",
            jamella: "Jamella",
            tyrael: "Tyrael",
            larzuk : "Larzuk",
            malah: "Malah",
            drehya: "Anya", //Anya
            nihlathak: "Nihlathak",
            qualkehk: "Qual-Kehk",
            izual: "Izual",
            navi: "Flavie", //Flavie
            malachai: "Hadriel", //Hadriel
        },
        Language::German => Translations {
            map_settings: "Karteneinstellungen",
            map_scale: "Kartenmaßstab",
            map_opacity: "Kartentransparenz",
            always_show_map: "Karte immer anzeigen",
            hide_map_in_menus: "Karte in Menüs verstecken",
            map_position: "Kartenposition",
            center: "Mitte",
            top_left: "Oben links",
            top_right: "Oben rechts",
            map_objects: "Kartenobjekte",
            show_chests: "Truhen anzeigen",
            size: "Größe",
            show_portals: "Portale anzeigen",
            show_shrines: "Schreine anzeigen",
            text_size: "Textgröße",
            monsters: "Monster",
            show_immunities: "Immunitäten anzeigen",
            normal_mobs: "Normale Mobs",
            minions: "Diener",
            champions: "Champions",
            uniques: "Einzigartige",
            bosses: "Bosse",
            lines_and_pathfinding: "Linien/Wegfindung",
            show_waypoint_lines: "Wegpunkte anzeigen",
            show_exit_lines: "Ausgänge anzeigen",
            show_quest_lines: "Questlinien anzeigen", 
            show_boss_lines: "Bosslinien anzeigen",
            missiles: "Geschosse",
            show_missiles: "Geschosse anzeigen",
            fire: "Feuer",
            cold: "Kälte",
            poison: "Gift",
            lightning: "Blitz",
            physical: "Physisch",
            magic: "Magie",
            quit: "Beenden",
            save_settings: "Einstellungen speichern",
            kashya: "Kaschya",
            akara: "Akara",
            deckardcain: "Deckard Cain",
            charsi: "Charsi",
            warriv: "Warriv",
            gheed: "Gheed",
            lysander: "Lysander", 
            geglash: "Geglasch",
            greiz: "Griez",
            jerhyn: "Jerhyn",
            drognan: "Drognan",
            atma: "Atma",
            elzix: "Elzix",
            meshif: "Meschif",
            kaelan: "Kaelan",
            fara: "Fara",
            asheara: "Aschara",
            natalya: "Natalya",
            alkor: "Alkor",
            ormus: "Ormus",
            hratli: "Hratli",
            halbu: "Halbu",
            jamella: "Jamella",
            tyrael: "Tyrael",
            larzuk : "Larzuk",
            malah: "Malah",
            drehya: "Anya", //Anya
            nihlathak: "Nihlathak",
            qualkehk: "Qua-Kehk",
            izual: "Izual",
            navi: "Flavie", //Flavie
            malachai: "Hadriel", //Hadriel
        },
        Language::TraditionalChinese => Translations {
            map_settings: "地圖設定",
            map_scale: "地圖縮放",
            map_opacity: "地圖透明度",
            always_show_map: "總是顯示地圖",
            hide_map_in_menus: "選單顯示時隱藏地圖",
            map_position: "地圖位置",
            center: "中央",
            top_left: "左上",
            top_right: "右上",
            map_objects: "地圖物件",
            show_chests: "顯示寶箱",
            size: "大小",
            show_portals: "顯示傳送門",
            show_shrines: "顯示神殿",
            text_size: "文字大小",
            monsters: "怪物",
            show_immunities: "顯示免疫",
            normal_mobs: "普通怪物",
            minions: "小兵",
            champions: "冠軍怪物",
            uniques: "獨特怪物",
            bosses: "首領",
            lines_and_pathfinding: "路線/尋路",
            show_waypoint_lines: "顯示路點線",
            show_exit_lines: "顯示出口線",
            show_quest_lines: "顯示任務線",
            show_boss_lines: "顯示首領線",
            missiles: "飛彈",
            show_missiles: "顯示飛彈",
            fire: "火",
            cold: "冷",
            poison: "毒",
            lightning: "閃電",
            physical: "物理",
            magic: "魔法",
            quit: "退出",
            save_settings: "保存設定",
            kashya: "卡夏",
            akara: "阿卡拉",
            deckardcain: "迪卡 凱恩",
            charsi: "恰西",
            warriv: "瓦瑞夫",
            gheed: "基得",
            lysander: "雷山德", 
            geglash: "基格列斯",
            greiz: "格雷茲",
            jerhyn: "傑海因",
            drognan: "卓格南",
            atma: "亞特瑪",
            elzix: "艾吉斯",
            meshif: "馬席夫",
            kaelan: "凱倫",
            fara: "F法拉",
            asheara: "艾席拉",
            natalya: "娜塔亞",
            alkor: "艾柯",
            ormus: "奧瑪斯",
            hratli: "赫拉鐵力",
            halbu: "海爾布",
            jamella: "賈梅拉",
            tyrael: "泰瑞爾",
            larzuk : "拉蘇克",
            malah: "馬拉",
            drehya: "安亞", //Anya
            nihlathak: "尼拉塞克",
            qualkehk: "誇爾凱克",
            izual: "依卒爾",
            navi: "弗拉維", //Flavie
            malachai: "哈德爾", //Hadriel
        },
        Language::Bogan => Translations {
            map_settings: "Map Settins",
            map_scale: "How Bigga Map",
            map_opacity: "See-Through-ness",
            always_show_map: "Always Chuck The Map Up",
            hide_map_in_menus: "Hide The Bloody Map in Menus",
            map_position: "Where's The Map At",
            center: "Smack Bang",
            top_left: "Up Left Corner, Mate",
            top_right: "Up Right Corner, Cobber",
            map_objects: "Stuff On The Map",
            show_chests: "Show Them Looties",
            size: "How Big?",
            show_portals: "Show Them Magic Doorways",
            show_shrines: "Show Them Holy Spots",
            text_size: "How Big's Them Words?",
            monsters: "The Buggers",
            show_immunities: "Show What Don't Kill 'Em",
            normal_mobs: "The normal cunts",
            minions: "The minion cunts",
            champions: "The champion cunts",
            uniques: "The unique cunts",
            bosses: "The boss cunts",
            lines_and_pathfinding: "Lines 'n Finding Ya Way",
            show_waypoint_lines: "Show The Go-Here Lines",
            show_exit_lines: "Show The Get-Out Lines",
            show_quest_lines: "Show The Adventure Lines", 
            show_boss_lines: "Show The Big Boss Lines",
            missiles: "The Shooties",
            show_missiles: "Show The Shooties",
            fire: "Burnies",
            cold: "Frosties",
            poison: "Sickies",
            lightning: "Zappies",
            physical: "Punchies",
            magic: "Wooies",
            quit: "Oi, Fuck Off, Yeah?",
            save_settings: "Save Ya Stuff",
            kashya: "Fatty Cracker",
            akara: "Ambo GILF",
            deckardcain: "Old Fella",
            charsi: "Hammer Sheila",
            warriv: "Outback Roo Fucka",
            gheed: "Dodgy Deala",
            lysander: "Cat Piss Seller", 
            geglash: "Boozer Bloke",
            greiz: "Offsider Provider",
            jerhyn: "Duchess Dickhead",
            drognan: "Harry Potter",
            atma: "Mate's Rate Giver",
            elzix: "Pokies Man",
            meshif: "Tinny Skipper",
            kaelan: "Motorbike Ashtray",
            fara: "Mallee Cow",
            asheara: "Use A Franger",
            natalya: "Shootin' Through",
            alkor: "Tallie Flicka",
            ormus: "Budgie Smugglers",
            hratli: "Op Shop",
            halbu: "Garbo",
            jamella: "Buckleys",
            tyrael: "London To A Brick",
            larzuk : "Mallee Bull ",
            malah: "Oldy Slag",
            drehya: "Dinky Di", //Anya
            nihlathak: "Cat Burying Shit",
            qualkehk: "Brick Shithouse",
            izual: "Figjam",
            navi: "Standover Woman", //Flavie
            malachai: "Battler Beyond the Black Stump", //Hadriel
        },
        Language::French => Translations {
            map_settings: "Paramètres de la carte",
            map_scale: "Échelle de la carte",
            map_opacity: "Opacité de la carte",
            always_show_map: "Toujours afficher la carte",
            hide_map_in_menus: "Cacher la carte dans les menus",
            map_position: "Position de la carte",
            center: "Centre",
            top_left: "En haut à gauche",
            top_right: "En haut à droite",
            map_objects: "Objets sur la carte",
            show_chests: "Afficher les coffres",
            size: "Taille",
            show_portals: "Afficher les portails",
            show_shrines: "Afficher les sanctuaires",
            text_size: "Taille du texte",
            monsters: "Monstres",
            show_immunities: "Afficher les immunités",
            normal_mobs: "Monstres normaux",
            minions: "Serviteurs",
            champions: "Champions",
            uniques: "Uniques",
            bosses: "Boss",
            lines_and_pathfinding: "Lignes/Guidage",
            show_waypoint_lines: "Afficher les lignes de points de passage",
            show_exit_lines: "Afficher les lignes de sortie",
            show_quest_lines: "Afficher les lignes de quête",
            show_boss_lines: "Afficher les lignes de boss",
            missiles: "Missiles",
            show_missiles: "Afficher les missiles",
            fire: "Feu",
            cold: "Froid",
            poison: "Poison",
            lightning: "Foudre",
            physical: "Physique",
            magic: "Magique",
            quit: "Quitter",
            save_settings: "Sauvegarder les paramètres",
            kashya: "Kashya",
            akara: "Akara",
            deckardcain: "Deckard Cain",
            charsi: "Charsi",
            warriv: "Warriv",
            gheed: "Gheed",
            lysander: "Lysander", 
            geglash: "Geglash",
            greiz: "Greiz",
            jerhyn: "Jerhyn",
            drognan: "Drognan",
            atma: "Atma",
            elzix: "Elzix",
            meshif: "Meshif",
            kaelan: "Kaelan",
            fara: "Fara",
            asheara: "Asheara",
            natalya: "Natalya",
            alkor: "Alkor",
            ormus: "Ormus",
            hratli: "Hratli",
            halbu: "Halbu",
            jamella: "Jamella",
            tyrael: "Tyraël",
            larzuk : "Larzuk",
            malah: "Malah",
            drehya: "Anya", //Anya
            nihlathak: "Nihlathak",
            qualkehk: "Qual-Kehk",
            izual: "Izual",
            navi: "Flavie", //Flavie
            malachai: "Hadriel", //Hadriel
        },
        Language::Italian => Translations {
            map_settings: "Impostazioni mappa",
            map_scale: "Scala mappa",
            map_opacity: "Opacità mappa",
            always_show_map: "Mostra sempre mappa",
            hide_map_in_menus: "Nascondi mappa nei menu",
            map_position: "Posizione mappa",
            center: "Centro",
            top_left: "In alto a sinistra",
            top_right: "In alto a destra",
            map_objects: "Oggetti mappa",
            show_chests: "Mostra bauli",
            size: "Dimensione",
            show_portals: "Mostra portali",
            show_shrines: "Mostra santuari",
            text_size: "Dimensione testo",
            monsters: "Mostri",
            show_immunities: "Mostra immunità",
            normal_mobs: "Mob normali",
            minions: "Servitori",
            champions: "Campioni",
            uniques: "Unici",
            bosses: "Boss",
            lines_and_pathfinding: "Linee/Trovapercorsi",
            show_waypoint_lines: "Mostra linee dei punti di passaggio",
            show_exit_lines: "Mostra linee di uscita",
            show_quest_lines: "Mostra linee delle missioni",
            show_boss_lines: "Mostra linee dei boss",
            missiles: "Missili",
            show_missiles: "Mostra missili",
            fire: "Fuoco",
            cold: "Freddo",
            poison: "Veleno",
            lightning: "Fulmine",
            physical: "Fisico",
            magic: "Magico",
            quit: "Esci",
            save_settings: "Salva impostazioni",
            kashya: "Kashya",
            akara: "Akara",
            deckardcain: "Deckard Cain",
            charsi: "Charsi",
            warriv: "Warriv",
            gheed: "Gheed",
            lysander: "Lysander", 
            geglash: "Geglash",
            greiz: "Greiz",
            jerhyn: "Jerhyn",
            drognan: "Drognan",
            atma: "Atma",
            elzix: "Elzix",
            meshif: "Meshif",
            kaelan: "Kaelan",
            fara: "Fara",
            asheara: "Asheara",
            natalya: "Natalya",
            alkor: "Alkor",
            ormus: "Ormus",
            hratli: "Hratli",
            halbu: "Halbu",
            jamella: "Jamella",
            tyrael: "Tyrael",
            larzuk : "Larzuk",
            malah: "Malah",
            drehya: "Anya", //Anya
            nihlathak: "Nihlathak",
            qualkehk: "Qual-Kehk",
            izual: "Izual",
            navi: "Flavie", //Flavie
            malachai: "Hadriel", //Hadriel
        },
        Language::Korean => Translations {
            map_settings: "지도 설정",
            map_scale: "지도 크기",
            map_opacity: "지도 불투명도",
            always_show_map: "지도 항상 표시",
            hide_map_in_menus: "메뉴가 표시될 때 지도 숨기기",
            map_position: "지도 위치",
            center: "중앙",
            top_left: "왼쪽 상단",
            top_right: "오른쪽 상단",
            map_objects: "지도 객체",
            show_chests: "상자 표시",
            size: "크기",
            show_portals: "포털 표시",
            show_shrines: "신사 표시",
            text_size: "텍스트 크기",
            monsters: "몬스터",
            show_immunities: "면역 표시",
            normal_mobs: "일반 몹",
            minions: "미니언",
            champions: "챔피언",
            uniques: "유니크",
            bosses: "보스",
            lines_and_pathfinding: "라인/경로 찾기",
            show_waypoint_lines: "웨이포인트 라인 표시",
            show_exit_lines: "출구 라인 표시",
            show_quest_lines: "퀘스트 라인 표시",
            show_boss_lines: "보스 라인 표시",
            missiles: "미사일",
            show_missiles: "미사일 표시",
            fire: "불",
            cold: "냉기",
            poison: "독",
            lightning: "번개",
            physical: "물리",
            magic: "마법",
            quit: "종료",
            save_settings: "설정 저장",            
            kashya: "카샤",
            akara: "아카라",
            deckardcain: "데커드 케인",
            charsi: "찰시",
            warriv: "와리브",
            gheed: "기드",
            lysander: "라이샌더", 
            geglash: "게글라시",
            greiz: "그레이즈",
            jerhyn: "제르힌",
            drognan: "드로그난",
            atma: "아트마",
            elzix: "엘직스",
            meshif: "메시프",
            kaelan: "캘란",
            fara: "파라",
            asheara: "아시아라",
            natalya: "나탈랴",
            alkor: "알코어",
            ormus: "오르무스",
            hratli: "흐라틀리",
            halbu: "할부",
            jamella: "자멜라",
            tyrael: "티리엘",
            larzuk : "라르주크",
            malah: "말라",
            drehya: "안야", //Anya
            nihlathak: "니흘라탁",
            qualkehk: "콸케크",
            izual: "이주알",
            navi: "플라비", //Flavie
            malachai: "하드리엘", //Hadriel
        },
        Language::Dutch => Translations {
            map_settings: "Kaartinstellingen",
            map_scale: "Kaartschaal",
            map_opacity: "Kaartdoorzichtigheid",
            always_show_map: "Kaart altijd tonen",
            hide_map_in_menus: "Kaart verbergen bij menu's",
            map_position: "Kaartpositie",
            center: "Centrum",
            top_left: "Linksboven",
            top_right: "Rechtsboven",
            map_objects: "Kaartobjecten",
            show_chests: "Kisten tonen",
            size: "Grootte",
            show_portals: "Portalen tonen",
            show_shrines: "Heiligdommen tonen",
            text_size: "Tekstgrootte",
            monsters: "Monsters",
            show_immunities: "Immunities tonen",
            normal_mobs: "Normale mobs",
            minions: "Handlangers",
            champions: "Kampioenen",
            uniques: "Unieken",
            bosses: "Bazen",
            lines_and_pathfinding: "Lijnen/Padvinding",
            show_waypoint_lines: "Wegwijzerlijnen tonen",
            show_exit_lines: "Uitganglijnen tonen",
            show_quest_lines: "Questlijnen tonen",
            show_boss_lines: "Baaslijnen tonen",
            missiles: "Raketten",
            show_missiles: "Raketten tonen",
            fire: "Vuur",
            cold: "Kou",
            poison: "Vergif",
            lightning: "Bliksem",
            physical: "Fysiek",
            magic: "Magie",
            quit: "Stoppen",
            save_settings: "Instellingen opslaan",
            kashya: "Kashya",
            akara: "Akara",
            deckardcain: "Deckard Cain",
            charsi: "Charsi",
            warriv: "Warriv",
            gheed: "Gheed",
            lysander: "Lysander", 
            geglash: "Geglash",
            greiz: "Greiz",
            jerhyn: "Jerhyn",
            drognan: "Drognan",
            atma: "Atma",
            elzix: "Elzix",
            meshif: "Meshif",
            kaelan: "Kaelan",
            fara: "Fara",
            asheara: "Asheara",
            natalya: "Natalya",
            alkor: "Alkor",
            ormus: "Ormus",
            hratli: "Hratli",
            halbu: "Halbu",
            jamella: "Jamella",
            tyrael: "Tyrael",
            larzuk : "Larzuk",
            malah: "Malah",
            drehya: "Anya", //Anya
            nihlathak: "Nihlathak",
            qualkehk: "Qual-Kehk",
            izual: "Izual",
            navi: "Flavie", //Flavie
            malachai: "Hadriel", //Hadriel
        },        
    }
}
