[general]
debug = true
d2lodpath = "bin/d2lod"
blacha_exe = "bin/d2-mapgen.exe"
render_scale = 1.0
fps_limit = 60
title = "Diablo II: Resurrected"
map_position = "Center"
multisampling = 8
vsync = true
high_dpi = true

[visual]
scale = 3.3
map_opacity = 0.65
always_show_map = true
hide_map_menus_open = true

[missiles]
enabled = true
fire_size = 3.0
fire_color = [255, 0, 0, 127]
cold_size = 3.0
cold_color = [0, 208, 255, 127]
poison_size = 3.0
poison_color = [50, 205, 50, 127]
lightning_size = 3.0
lightning_color = [255, 255, 0, 70]
physical_size = 3.0
physical_color = [205, 133, 63, 127]
magic_size = 3.0
magic_color = [255, 136, 0, 127]

[chests]
enabled = true
size = 0.1

[portals]
enabled = true
size = 2.0

[shrines]
enabled = true
size = 0.1
text_size = 5.0

[lines]
waypoint_enabled = false
waypoint_path_enabled = false
waypoint_rgba = [255, 255, 0, 127]
exit_enabled = true
exit_path_enabled = false
exit_rgba = [255, 0, 255, 127]
quest_enabled = false
quest_path_enabled = true
quest_rgba = [0, 255, 0, 127]
boss_enabled = true
boss_path_enabled = false
boss_rgba = [255, 0, 0, 127]

[monsters]
immunities = true
normal_mobs = true
normal_mobs_size = 1.5
normal_mob_color = [255, 255, 255, 255]
minions_mobs = true
minions_mobs_size = 1.5
minions_mob_color = [255, 255, 255, 255]
champions_mobs = true
champions_mobs_size = 3.0
champions_mob_color = [96, 92, 216, 255]
unique_mobs = true
unique_mobs_size = 3.0
unique_mob_color = [212, 175, 55, 255]
boss_mobs = true
boss_mobs_size = 3.0
boss_mob_color = [255, 0, 0, 255]
