use num_derive::FromPrimitive;
use num_traits::FromPrimitive;
use strum::Display;
use strum::EnumString;

use crate::memory::process::D2RInstance;
use crate::memory::structs::Unit;
use crate::memory::structs::{ItemData, StaticPath};

use super::affixes::ItemPrefixSuffix;
use super::affixes::read_affixes;
use super::stats::Stat;
use super::stats::StatEnum;
use super::stats::read_stats;
use convert_case::Case;
use convert_case::Casing;

use crate::LOCALISATION;

#[derive(Debug, Clone, Hash)]
pub struct ItemUnit {
    pub unit_id: u32,
    pub txt_file_no: BaseItem,
    pub mode: ItemMode,
    pub dw_owner_id: u32,
    pub pos_x: u32,
    pub pos_y: u32,
    pub p_path: u64,
    pub p_unit_data: u64,
    pub quality: Quality,
    pub flags: u32,
    pub inv_page: InvPage,
    pub body_location: BodyLocation,
    pub item_stats: Vec<Stat>,
    pub num_sockets: u8,
    pub set_item_name: Option<SetItemName>,
    pub unique_item_name: Option<UniqueItemName>,
    pub item_prefixes: ItemPrefixSuffix,
}

impl ItemUnit {
    pub fn new(d2rprocess: &D2RInstance, unit: Unit) -> Option<Self> {
        let txt_file_no: BaseItem = BaseItem::from_u32(unit.txt_file_no).unwrap_or_default();
        let mode = ItemMode::from_u32(unit.mode).unwrap_or_default();
        let (pos_x, pos_y) = Self::get_static_position(d2rprocess, unit);

        let item_data: ItemData = d2rprocess.read_mem::<ItemData>(unit.p_unit_data);
        let quality = match Quality::from_u32(item_data.quality) {
            Some(q) => q,
            None => return None
        };
        let inv_page = InvPage::from_u8(item_data.inv_page).unwrap_or_default();
        let body_location = BodyLocation::from_u8(item_data.body_loc).unwrap_or_default();
        let item_stats = Self::get_item_stats(d2rprocess, unit);
        let item_prefixes = Self::get_item_prefixes(item_data);

        let num_sockets: u8 = match item_stats.iter().find(|s| s.stat == StatEnum::NumSockets) {
            Some(stat) => stat.value.try_into().unwrap(),
            None => 0,
        };

        let set_item_name: Option<SetItemName> = if quality == Quality::Set && item_data.file_text > 0 {
            SetItemName::from_u32(item_data.file_text)
        } else if quality == Quality::Set {
            Self::get_setitem_from_base_id(&txt_file_no)
        } else {
            None
        };
        let unique_item_name: Option<UniqueItemName> = if quality == Quality::Unique && item_data.file_text > 0 {
            UniqueItemName::from_u32(item_data.file_text)
        } else if quality == Quality::Unique {
            Self::get_uniqueitem_from_base_id(&txt_file_no)
        } else {
            None
        };

        Some(ItemUnit {
            unit_id: unit.unit_id,
            txt_file_no,
            mode,
            dw_owner_id: item_data.dw_owner_id,
            pos_x,
            pos_y,
            p_path: unit.p_path,
            p_unit_data: unit.p_unit_data,
            quality,
            flags: item_data.flags,
            inv_page,
            body_location,
            item_stats,
            num_sockets,
            set_item_name,
            unique_item_name,
            item_prefixes
        })
    }
    
    pub fn get_tts_description(&self) -> String {
        if self.set_item_name.is_some() {
            format!("{:?} {:?}", self.set_item_name.as_ref().unwrap(), self.txt_file_no).to_case(Case::Title)
        } else if self.unique_item_name.is_some() {
            format!("{:?} {:?}", self.unique_item_name.as_ref().unwrap(), self.txt_file_no).to_case(Case::Title)
        } else {
            if self.quality == Quality::Normal {
                format!("{:?}",self.txt_file_no).to_case(Case::Title)
            } else {
                format!("{:?} {:?}", self.quality, self.txt_file_no).to_case(Case::Title)
            }
        }
    }

    pub fn get_item_log_name(&self, show_prefix_suffix: bool) -> String {
        let eth = if self.is_ethereal() {
            String::from(format!(" (Eth)"))
        } else {
            String::new()
        };
        let sockets = if self.num_sockets > 0 {
            String::from(format!(" ({:?})", self.num_sockets))
        } else {
            String::new()
        };
        if self.set_item_name.is_some() {
            if self.mode == ItemMode::OnGround || self.mode == ItemMode::Dropping {
                format!("{:?} {:?}{}{}", self.set_item_name.as_ref().unwrap(), self.txt_file_no, eth, sockets).to_case(Case::Title)
            } else {
                format!("{:?} {:?}{}{} (Picked up)", self.set_item_name.as_ref().unwrap(), self.txt_file_no, eth, sockets).to_case(Case::Title)
            }
            
        } else if self.unique_item_name.is_some() {
            if self.mode == ItemMode::OnGround || self.mode == ItemMode::Dropping {
                format!("{:?} {:?}{}{}", self.unique_item_name.as_ref().unwrap(), self.txt_file_no, eth, sockets).to_case(Case::Title)
            } else {
                format!("{:?} {:?}{}{} (Picked up)", self.unique_item_name.as_ref().unwrap(), self.txt_file_no, eth, sockets).to_case(Case::Title)
            }
            
        } else if self.quality == Quality::Magic && show_prefix_suffix {
            let mut magic_name = format!("{:?}", self.txt_file_no);
            if !self.item_prefixes.magic_prefix_name.is_empty() {
                magic_name = format!("{} {}", self.item_prefixes.magic_prefix_name, magic_name)
            }
            if !self.item_prefixes.magic_suffix_name.is_empty() {
                magic_name = format!("{} {}", magic_name, self.item_prefixes.magic_suffix_name)
            }
            if self.mode == ItemMode::OnGround || self.mode == ItemMode::Dropping {
                format!("{}{}{}", magic_name, eth, sockets).to_case(Case::Title)
            } else {
                format!("{}{}{} (Picked up)", magic_name, eth, sockets).to_case(Case::Title)
            }
        } else if self.quality == Quality::Rare && show_prefix_suffix {
            let mut rare_name = format!("{:?}", self.txt_file_no);
            if !self.item_prefixes.rare_suffix_name.is_empty() {
                rare_name = format!("{}\n{}", self.item_prefixes.rare_suffix_name, rare_name)
            }
            if !self.item_prefixes.rare_prefix_name.is_empty() {
                rare_name = format!("{} {}", self.item_prefixes.rare_prefix_name, rare_name)
            }

            if self.mode == ItemMode::OnGround || self.mode == ItemMode::Dropping {
                format!("{}{}{}", rare_name, eth, sockets).to_case(Case::Title)
            } else {
                format!("{}{}{} (Picked up)", rare_name, eth, sockets).to_case(Case::Title)
            }
        } else {
            // let localisation = LOCALISATION.lock().unwrap();
            // let base_name = format!("{:?}", self.txt_file_no);
            // let item_name = localisation.get_item_name(&base_name);
            
            if self.mode == ItemMode::OnGround || self.mode == ItemMode::Dropping {
                format!("{}{}{}", self.txt_file_no, eth, sockets).to_case(Case::Title)
            } else {
                format!("{}{}{} (Picked up)", self.txt_file_no, eth, sockets).to_case(Case::Title)
            }
        }
    }

    pub fn get_item_ground_alert_name(&self, show_prefix_suffix: bool) -> String {
        let eth = if self.is_ethereal() {
            String::from(format!(" (Eth)"))
        } else {
            String::new()
        };
        let sockets = if self.num_sockets > 0 {
            String::from(format!(" ({:?})", self.num_sockets))
        } else {
            String::new()
        };
        if self.set_item_name.is_some() {
            format!("{:?}\n {:?}{}{}", self.set_item_name.as_ref().unwrap(), self.txt_file_no, eth, sockets).to_case(Case::Title)
        } else if self.unique_item_name.is_some() {
            format!("{:?}\n {:?}{}{}", self.unique_item_name.as_ref().unwrap(), self.txt_file_no, eth, sockets).to_case(Case::Title)
        } else if self.quality == Quality::Magic && show_prefix_suffix {
            let mut magic_name = format!("{:?}", self.txt_file_no);
            if !self.item_prefixes.magic_prefix_name.is_empty() {
                magic_name = format!("{} {}", self.item_prefixes.magic_prefix_name, magic_name)
            }
            if !self.item_prefixes.magic_suffix_name.is_empty() {
                magic_name = format!("{} {}", magic_name, self.item_prefixes.magic_suffix_name)
            }
            format!("{}{}{}", magic_name, eth, sockets).to_case(Case::Title)
        } else if self.quality == Quality::Rare && show_prefix_suffix {
            let mut rare_name = format!("{:?}", self.txt_file_no);
            if !self.item_prefixes.rare_suffix_name.is_empty() {
                rare_name = format!("{}\n{}", self.item_prefixes.rare_suffix_name, rare_name)
            }
            if !self.item_prefixes.rare_prefix_name.is_empty() {
                rare_name = format!("{} {}", self.item_prefixes.rare_prefix_name, rare_name)
            }
            format!("{}{}{}", rare_name, eth, sockets).to_case(Case::Title)
        } else {
            format!("{:?}{}{}", self.txt_file_no, eth, sockets).to_case(Case::Title)
        }
    }

    pub fn get_static_position(d2rprocess: &D2RInstance, unit: Unit) -> (u32, u32) {
        if unit.p_path == 0 {
            (0, 0)
        } else {
            let item_path: StaticPath = d2rprocess.read_mem::<StaticPath>(unit.p_path);
            let pos_x: u32 = item_path.x;
            let pos_y: u32 = item_path.y;
            (pos_x, pos_y)
        }
    }

    pub fn get_item_stats(d2rprocess: &D2RInstance, unit: Unit) -> Vec<Stat> {
        if unit.p_stats_list_ex == 0 {
            vec![]
        } else {
            read_stats(d2rprocess, &unit)
        }
    }

    pub fn get_item_prefixes(item_data: ItemData) -> ItemPrefixSuffix {
        read_affixes(&item_data)
    }

    #[allow(dead_code)]
    pub fn on_inventory(&self, player_unit_id: u32) -> bool {
        if self.body_location != BodyLocation::Unknown { // ON BODY
            if self.inv_page == InvPage::Belt || self.inv_page == InvPage::Inventory || self.inv_page == InvPage::Null {
                if self.mode == ItemMode::InBelt || self.mode == ItemMode::Stored || self.mode == ItemMode::Equipped {
                    if self.dw_owner_id == player_unit_id {
                        return true;
                    }
                }
            }
        }
        false
    }

    #[allow(dead_code)]
    pub fn on_belt(&self, player_unit_id: u32) -> bool {
        if self.mode == ItemMode::InBelt {
            if self.dw_owner_id == player_unit_id {
                return true;
            }
        }
        false
    }


    #[allow(dead_code)]
    pub fn is_quest_item(txt_file_no: BaseItem) -> bool {
        matches!(
            txt_file_no,
            BaseItem::TheGidbinn
                | BaseItem::WirtsLeg
                | BaseItem::HoradricMalus
                | BaseItem::HellforgeHammer
                | BaseItem::HoradricStaff
                | BaseItem::StaffOfKings
                | BaseItem::KhalimsFlail
                | BaseItem::AmuletOfTheViper
                | BaseItem::KhalimsEye
                | BaseItem::KhalimsHeart
                | BaseItem::KhalimsBrain
                | BaseItem::ScrollOfInifuss
                | BaseItem::HoradricCube
                | BaseItem::HoradricScroll
                | BaseItem::MephistosSoulstone
                | BaseItem::BookOfSkill
        )
    }

    pub fn get_setitem_from_base_id(txt_file_no: &BaseItem) -> Option<SetItemName> {
        match txt_file_no {
            BaseItem::LargeShield => Some(SetItemName::CiverbsWard),
            BaseItem::GrandScepter => Some(SetItemName::CiverbsCudgel),
            BaseItem::ChainBoots => Some(SetItemName::HsarusIronHeel),
            BaseItem::Buckler => Some(SetItemName::HsarusIronFist),
            BaseItem::LongSword => Some(SetItemName::CleglawsTooth),
            BaseItem::SmallShield => Some(SetItemName::CleglawsClaw),
            BaseItem::ChainGloves => Some(SetItemName::CleglawsPincers),
            BaseItem::BroadSword => Some(SetItemName::IsenhartsLightbrand),
            BaseItem::GothicShield => Some(SetItemName::IsenhartsParry),
            BaseItem::BreastPlate => Some(SetItemName::IsenhartsCase),
            BaseItem::FullHelm => Some(SetItemName::IsenhartsHorns),
            BaseItem::LongBattleBow => Some(SetItemName::VidalasBarb),
            BaseItem::LightPlatedBoots => Some(SetItemName::VidalasFetlock),
            BaseItem::LeatherArmor => Some(SetItemName::VidalasAmbush),
            BaseItem::KiteShield => Some(SetItemName::MilabregasOrb),
            BaseItem::WarScepter => Some(SetItemName::MilabregasRod),
            BaseItem::AncientArmor => Some(SetItemName::MilabregasRobe),
            BaseItem::BattleStaff => Some(SetItemName::CathansRule),
            BaseItem::ChainMail => Some(SetItemName::CathansMesh),
            BaseItem::Mask => Some(SetItemName::CathansVisage),
            BaseItem::MilitaryPick => Some(SetItemName::TancredsCrowbill),
            BaseItem::FullPlateMail => Some(SetItemName::TancredsSpine),
            BaseItem::Boots => Some(SetItemName::TancredsHobnails),
            BaseItem::BoneHelm => Some(SetItemName::TancredsSkull),
            BaseItem::Gauntlets => Some(SetItemName::SigonsGage),
            BaseItem::GreatHelm => Some(SetItemName::SigonsVisor),
            BaseItem::GothicPlate => Some(SetItemName::SigonsShelter),
            BaseItem::Greaves => Some(SetItemName::SigonsSabot),
            BaseItem::PlatedBelt => Some(SetItemName::SigonsWrap),
            BaseItem::TowerShield => Some(SetItemName::SigonsGuard),
            BaseItem::GrimWand => Some(SetItemName::InfernalTorch),
            BaseItem::Helm => Some(SetItemName::BerserkersHeadgear),
            BaseItem::SplintMail => Some(SetItemName::BerserkersHauberk),
            BaseItem::DoubleAxe => Some(SetItemName::BerserkersHatchet),
            BaseItem::LeatherGloves => Some(SetItemName::DeathsHand),
            BaseItem::Sash => Some(SetItemName::DeathsGuard),
            BaseItem::WarSword => Some(SetItemName::DeathsTouch),
            BaseItem::Sabre => Some(SetItemName::AngelicSickle),
            BaseItem::RingMail => Some(SetItemName::AngelicMantle),
            BaseItem::ShortWarBow => Some(SetItemName::ArcticHorn),
            BaseItem::QuiltedArmor => Some(SetItemName::ArcticFurs),
            BaseItem::LightBelt => Some(SetItemName::ArcticBinding),
            BaseItem::WarStaff => Some(SetItemName::ArcannasDeathwand),
            BaseItem::SkullCap => Some(SetItemName::ArcannasHead),
            BaseItem::LightPlate => Some(SetItemName::ArcannasFlesh),
            BaseItem::GrimHelm => Some(SetItemName::NatalyasTotem),
            BaseItem::ScissorsSuwayyah => Some(SetItemName::NatalyasMark),
            BaseItem::LoricatedMail => Some(SetItemName::NatalyasShadow),
            BaseItem::MeshBoots => Some(SetItemName::NatalyasSoul),
            BaseItem::HuntersGuise => Some(SetItemName::AldursStonyGaze),
            BaseItem::ShadowPlate => Some(SetItemName::AldursDeception),
            BaseItem::JaggedStar => Some(SetItemName::AldursGauntlet),
            BaseItem::BattleBoots => Some(SetItemName::AldursAdvance),
            BaseItem::AvengerGuard => Some(SetItemName::ImmortalKingsWill),
            BaseItem::SacredArmor => Some(SetItemName::ImmortalKingsSoulCage),
            BaseItem::WarBelt => Some(SetItemName::ImmortalKingsDetail),
            BaseItem::WarGauntlets => Some(SetItemName::ImmortalKingsForge),
            BaseItem::WarBoots => Some(SetItemName::ImmortalKingsPillar),
            BaseItem::OgreMaul => Some(SetItemName::ImmortalKingsStoneCrusher),
            BaseItem::MeshBelt => Some(SetItemName::TalRashasFireSpunCloth),
            BaseItem::SwirlingCrystal => Some(SetItemName::TalRashasLidlessEye),
            BaseItem::LacqueredPlate => Some(SetItemName::TalRashasHowlingWind),
            BaseItem::DeathMask => Some(SetItemName::TalRashasHoradricCrest),
            BaseItem::Corona => Some(SetItemName::GriswoldsValor),
            BaseItem::OrnatePlate => Some(SetItemName::GriswoldsHeart),
            BaseItem::Caduceus => Some(SetItemName::GriswoldssRedemption),
            BaseItem::VortexShield => Some(SetItemName::GriswoldsHonor),
            BaseItem::BoneVisage => Some(SetItemName::TrangOulsGuise),
            BaseItem::ChaosArmor => Some(SetItemName::TrangOulsScales),
            BaseItem::CantorTrophy => Some(SetItemName::TrangOulsWing),
            BaseItem::HeavyBracers => Some(SetItemName::TrangOulsClaws),
            BaseItem::TrollBelt => Some(SetItemName::TrangOulsGirth),
            BaseItem::Diadem => Some(SetItemName::MavinasTrueSight),
            BaseItem::KrakenShell => Some(SetItemName::MavinasEmbrace),
            BaseItem::BattleGauntlets => Some(SetItemName::MavinasIcyClutch),
            BaseItem::SharkskinBelt => Some(SetItemName::MavinasTenet),
            BaseItem::GrandMatronBow => Some(SetItemName::MavinasCaster),
            BaseItem::BrambleMitts => Some(SetItemName::LayingOfHands),
            BaseItem::DemonhideBoots => Some(SetItemName::RiteOfPassage),
            BaseItem::DuskShroud => Some(SetItemName::SpiritualCustodian),
            BaseItem::MithrilCoil => Some(SetItemName::Credendum),
            BaseItem::ReinforcedMace => Some(SetItemName::DangoonsTeaching),
            BaseItem::Ward => Some(SetItemName::HeavensTaebaek),
            BaseItem::Cuirass => Some(SetItemName::HaemosusAdament),
            BaseItem::SpiredHelm => Some(SetItemName::OndalsAlmighty),
            BaseItem::WingedHelm => Some(SetItemName::GuillaumesFace),
            BaseItem::BattleBelt => Some(SetItemName::WilhelmsPride),
            BaseItem::SharkskinGloves => Some(SetItemName::MagnusSkin),
            BaseItem::RoundShield => Some(SetItemName::WihtstansGuard),
            BaseItem::GrandCrown => Some(SetItemName::HwaninsSplendor),
            BaseItem::TigulatedMail => Some(SetItemName::HwaninsRefuge),
            BaseItem::Bill => Some(SetItemName::HwaninsJustice),
            BaseItem::CrypticSword => Some(SetItemName::SazabisCobaltRedeemer),
            BaseItem::BalrogSkin => Some(SetItemName::SazabisGhostLiberator),
            BaseItem::Basinet => Some(SetItemName::SazabisMentalSheath),
            BaseItem::ColossusBlade => Some(SetItemName::BulKathosSacredCharge),
            BaseItem::MythicalSword => Some(SetItemName::BulKathosTribalGuardian),
            BaseItem::WarHat => Some(SetItemName::CowKingsHorns),
            BaseItem::StuddedLeather => Some(SetItemName::CowKingsHide),
            BaseItem::ElderStaff => Some(SetItemName::NajsPuzzler),
            BaseItem::HellforgePlate => Some(SetItemName::NajsLightPlate),
            BaseItem::Circlet => Some(SetItemName::NajsCirclet),
            BaseItem::HeavyGloves => Some(SetItemName::McAuleysTaboo),
            BaseItem::BoneWand => Some(SetItemName::McAuleysSuperstition),
            _ => None,
        }
    }

    pub fn get_uniqueitem_from_base_id(txt_file_no: &BaseItem) -> Option<UniqueItemName> {
        match txt_file_no {
            BaseItem::HandAxe => Some(UniqueItemName::TheGnasher),
            BaseItem::Axe => Some(UniqueItemName::Deathspade),
            BaseItem::DoubleAxe => Some(UniqueItemName::Bladebone),
            BaseItem::MilitaryPick => Some(UniqueItemName::Mindrend),
            BaseItem::WarAxe => Some(UniqueItemName::Rakescar),
            BaseItem::LargeAxe => Some(UniqueItemName::FechmarsAxe),
            BaseItem::BroadAxe => Some(UniqueItemName::Goreshovel),
            BaseItem::BattleAxe => Some(UniqueItemName::TheChieftan),
            BaseItem::GreatAxe => Some(UniqueItemName::Brainhew),
            BaseItem::GiantAxe => Some(UniqueItemName::TheHumongous),
            BaseItem::Wand => Some(UniqueItemName::IrosTorch),
            BaseItem::YewWand => Some(UniqueItemName::Maelstromwrath),
            BaseItem::BoneWand => Some(UniqueItemName::Gravenspine),
            BaseItem::GrimWand => Some(UniqueItemName::UmesLament),
            BaseItem::Club => Some(UniqueItemName::Felloak),
            BaseItem::Scepter => Some(UniqueItemName::KnellStriker),
            BaseItem::GrandScepter => Some(UniqueItemName::Rusthandle),
            BaseItem::WarScepter => Some(UniqueItemName::Stormeye),
            BaseItem::SpikedClub => Some(UniqueItemName::Stoutnail),
            BaseItem::Mace => Some(UniqueItemName::Crushflange),
            BaseItem::MorningStar => Some(UniqueItemName::Bloodrise),
            BaseItem::Flail => Some(UniqueItemName::TheGeneralsTanDoLiGa),
            BaseItem::WarHammer => Some(UniqueItemName::Ironstone),
            BaseItem::Maul => Some(UniqueItemName::Bonesob),
            BaseItem::GreatMaul => Some(UniqueItemName::Steeldriver),
            BaseItem::ShortSword => Some(UniqueItemName::RixotsKeen),
            BaseItem::Scimitar => Some(UniqueItemName::BloodCrescent),
            BaseItem::Sabre => Some(UniqueItemName::KrintizsSkewer),
            BaseItem::Falchion => Some(UniqueItemName::Gleamscythe),
            BaseItem::CrystalSword => Some(UniqueItemName::Azurewrath),
            BaseItem::BroadSword => Some(UniqueItemName::GriswoldsEdge),
            BaseItem::LongSword => Some(UniqueItemName::Hellplague),
            BaseItem::WarSword => Some(UniqueItemName::CulwensPoint),
            BaseItem::TwoHandedSword => Some(UniqueItemName::Shadowfang),
            BaseItem::Claymore => Some(UniqueItemName::Soulflay),
            BaseItem::GiantSword => Some(UniqueItemName::KinemilsAwl),
            BaseItem::BastardSword => Some(UniqueItemName::Blacktongue),
            BaseItem::Flamberge => Some(UniqueItemName::Ripsaw),
            BaseItem::GreatSword => Some(UniqueItemName::ThePatriarch),
            BaseItem::Dagger => Some(UniqueItemName::Gull),
            BaseItem::Dirk => Some(UniqueItemName::TheDiggler),
            BaseItem::Kris => Some(UniqueItemName::TheJadeTanDo),
            BaseItem::Blade => Some(UniqueItemName::IricesShard),
            BaseItem::Spear => Some(UniqueItemName::TheDragonChang),
            BaseItem::Trident => Some(UniqueItemName::Razortine),
            BaseItem::Brandistock => Some(UniqueItemName::Bloodthief),
            BaseItem::Spetum => Some(UniqueItemName::LanceOfYaggai),
            BaseItem::Pike => Some(UniqueItemName::TheTannrGorerod),
            BaseItem::Bardiche => Some(UniqueItemName::DimoaksHew),
            BaseItem::Voulge => Some(UniqueItemName::Steelgoad),
            BaseItem::Scythe => Some(UniqueItemName::SoulHarvest),
            BaseItem::Poleaxe => Some(UniqueItemName::TheBattlebranch),
            BaseItem::Halberd => Some(UniqueItemName::Woestave),
            BaseItem::WarScythe => Some(UniqueItemName::TheGrimReaper),
            BaseItem::ShortStaff => Some(UniqueItemName::BaneAsh),
            BaseItem::LongStaff => Some(UniqueItemName::SerpentLord),
            BaseItem::GnarledStaff => Some(UniqueItemName::LazarusSpire),
            BaseItem::BattleStaff => Some(UniqueItemName::TheSalamander),
            BaseItem::WarStaff => Some(UniqueItemName::TheIronJangBong),
            BaseItem::ShortBow => Some(UniqueItemName::Pluckeye),
            BaseItem::HuntersBow => Some(UniqueItemName::Witherstring),
            BaseItem::LongBow => Some(UniqueItemName::Rimeraven),
            BaseItem::CompositeBow => Some(UniqueItemName::Piercerib),
            BaseItem::ShortBattleBow => Some(UniqueItemName::Pullspite),
            BaseItem::LongBattleBow => Some(UniqueItemName::Wizendraw),
            BaseItem::ShortWarBow => Some(UniqueItemName::Hellclap),
            BaseItem::LongWarBow => Some(UniqueItemName::Blastbark),
            BaseItem::LightCrossbow => Some(UniqueItemName::Leadcrow),
            BaseItem::Crossbow => Some(UniqueItemName::Ichorsting),
            BaseItem::HeavyCrossbow => Some(UniqueItemName::Hellcast),
            BaseItem::RepeatingCrossbow => Some(UniqueItemName::Doomspittle),
            BaseItem::Cap => Some(UniqueItemName::WarBonnet),
            BaseItem::SkullCap => Some(UniqueItemName::Tarnhelm),
            BaseItem::Helm => Some(UniqueItemName::CoifOfGlory),
            BaseItem::FullHelm => Some(UniqueItemName::Duskdeep),
            BaseItem::BoneHelm => Some(UniqueItemName::Wormskull),
            BaseItem::GreatHelm => Some(UniqueItemName::Howltusk),
            BaseItem::Crown => Some(UniqueItemName::UndeadCrown),
            BaseItem::Mask => Some(UniqueItemName::TheFaceOfHorror),
            BaseItem::QuiltedArmor => Some(UniqueItemName::Greyform),
            BaseItem::LeatherArmor => Some(UniqueItemName::BlinkbatsForm),
            BaseItem::HardLeatherArmor => Some(UniqueItemName::TheCenturion),
            BaseItem::StuddedLeather => Some(UniqueItemName::Twitchthroe),
            BaseItem::RingMail => Some(UniqueItemName::Darkglow),
            BaseItem::ScaleMail => Some(UniqueItemName::Hawkmail),
            BaseItem::ChainMail => Some(UniqueItemName::SparkingMail),
            BaseItem::BreastPlate => Some(UniqueItemName::Venomsward),
            BaseItem::SplintMail => Some(UniqueItemName::Iceblink),
            BaseItem::PlateMail => Some(UniqueItemName::Boneflesh),
            BaseItem::FieldPlate => Some(UniqueItemName::Rockfleece),
            BaseItem::GothicPlate => Some(UniqueItemName::Rattlecage),
            BaseItem::FullPlateMail => Some(UniqueItemName::Goldskin),
            BaseItem::AncientArmor => Some(UniqueItemName::VictorsSilk),
            BaseItem::LightPlate => Some(UniqueItemName::HeavenlyGarb),
            BaseItem::Buckler => Some(UniqueItemName::PeltaLunata),
            BaseItem::SmallShield => Some(UniqueItemName::UmbralDisk),
            BaseItem::LargeShield => Some(UniqueItemName::Stormguild),
            BaseItem::BoneShield => Some(UniqueItemName::WallOfTheEyeless),
            BaseItem::SpikedShield => Some(UniqueItemName::SwordbackHold),
            BaseItem::KiteShield => Some(UniqueItemName::Steelclash),
            BaseItem::TowerShield => Some(UniqueItemName::BverritKeep),
            BaseItem::GothicShield => Some(UniqueItemName::TheWard),
            BaseItem::LeatherGloves => Some(UniqueItemName::TheHandOfBroc),
            BaseItem::HeavyGloves => Some(UniqueItemName::Bloodfist),
            BaseItem::ChainGloves => Some(UniqueItemName::ChanceGuards),
            BaseItem::LightGauntlets => Some(UniqueItemName::Magefist),
            BaseItem::Gauntlets => Some(UniqueItemName::Frostburn),
            BaseItem::Boots => Some(UniqueItemName::Hotspur),
            BaseItem::HeavyBoots => Some(UniqueItemName::Gorefoot),
            BaseItem::ChainBoots => Some(UniqueItemName::TreadsOfCthon),
            BaseItem::LightPlatedBoots => Some(UniqueItemName::GoblinToe),
            BaseItem::Greaves => Some(UniqueItemName::Tearhaunch),
            BaseItem::Sash => Some(UniqueItemName::LenymsCord),
            BaseItem::LightBelt => Some(UniqueItemName::Snakecord),
            BaseItem::Belt => Some(UniqueItemName::Nightsmoke),
            BaseItem::HeavyBelt => Some(UniqueItemName::Goldwrap),
            BaseItem::PlatedBelt => Some(UniqueItemName::Bladebuckle),
            BaseItem::AmuletOfTheViper => Some(UniqueItemName::AmuletOfTheViper),
            BaseItem::StaffOfKings => Some(UniqueItemName::StaffOfKings),
            BaseItem::HoradricStaff => Some(UniqueItemName::HoradricStaff),
            BaseItem::HellforgeHammer => Some(UniqueItemName::HellForgeHammer),
            BaseItem::KhalimsFlail => Some(UniqueItemName::KhalimFlail),
            BaseItem::KhalimsWill => Some(UniqueItemName::SuperKhalimFlail),
            BaseItem::Hatchet => Some(UniqueItemName::Coldkill),
            BaseItem::Cleaver => Some(UniqueItemName::ButchersPupil),
            BaseItem::TwinAxe => Some(UniqueItemName::Islestrike),
            BaseItem::Crowbill => Some(UniqueItemName::PompesWrath),
            BaseItem::Naga => Some(UniqueItemName::GuardianNaga),
            BaseItem::MilitaryAxe => Some(UniqueItemName::WarlordsTrust),
            BaseItem::BeardedAxe => Some(UniqueItemName::Spellsteel),
            BaseItem::Tabar => Some(UniqueItemName::Stormrider),
            BaseItem::GothicAxe => Some(UniqueItemName::BoneslayerBlade),
            BaseItem::AncientAxe => Some(UniqueItemName::TheMinataur),
            BaseItem::BurntWand => Some(UniqueItemName::SuicideBranch),
            BaseItem::PetrifiedWand => Some(UniqueItemName::CarinShard),
            BaseItem::TombWand => Some(UniqueItemName::ArmOfKingLeoric),
            BaseItem::GraveWand => Some(UniqueItemName::BlackhandKey),
            BaseItem::Cudgel => Some(UniqueItemName::DarkClanCrusher),
            BaseItem::RuneScepter => Some(UniqueItemName::ZakarumsHand),
            BaseItem::HolyWaterSprinkler => Some(UniqueItemName::TheFetidSprinkler),
            BaseItem::DivineScepter => Some(UniqueItemName::HandOfBlessedLight),
            BaseItem::BarbedClub => Some(UniqueItemName::Fleshrender),
            BaseItem::FlangedMace => Some(UniqueItemName::SureshrillFrost),
            BaseItem::JaggedStar => Some(UniqueItemName::Moonfall),
            BaseItem::Knout => Some(UniqueItemName::BaezilsVortex),
            BaseItem::BattleHammer => Some(UniqueItemName::Earthshaker),
            BaseItem::WarClub => Some(UniqueItemName::BloodtreeStump),
            BaseItem::MarteldeFer => Some(UniqueItemName::TheGavelOfPain),
            BaseItem::Gladius => Some(UniqueItemName::Bloodletter),
            BaseItem::Cutlass => Some(UniqueItemName::ColdsteelEye),
            BaseItem::Shamshir => Some(UniqueItemName::Hexfire),
            BaseItem::Tulwar => Some(UniqueItemName::BladeOfAliBaba),
            BaseItem::DimensionalBlade => Some(UniqueItemName::GinthersRift),
            BaseItem::BattleSword => Some(UniqueItemName::Headstriker),
            BaseItem::RuneSword => Some(UniqueItemName::PlagueBearer),
            BaseItem::AncientSword => Some(UniqueItemName::TheAtlantian),
            BaseItem::Espandon => Some(UniqueItemName::CrainteVomir),
            BaseItem::DacianFalx => Some(UniqueItemName::BingSzWang),
            BaseItem::TuskSword => Some(UniqueItemName::TheVileHusk),
            BaseItem::GothicSword => Some(UniqueItemName::Cloudcrack),
            BaseItem::Zweihander => Some(UniqueItemName::TodesfaelleFlamme),
            BaseItem::ExecutionerSword => Some(UniqueItemName::Swordguard),
            BaseItem::Poignard => Some(UniqueItemName::Spineripper),
            BaseItem::Rondel => Some(UniqueItemName::HeartCarver),
            BaseItem::Cinquedeas => Some(UniqueItemName::BlackbogsSharp),
            BaseItem::Stilleto => Some(UniqueItemName::Stormspike),
            BaseItem::WarSpear => Some(UniqueItemName::TheImpaler),
            BaseItem::Fuscina => Some(UniqueItemName::KelpieSnare),
            BaseItem::WarFork => Some(UniqueItemName::SoulfeastTine),
            BaseItem::Yari => Some(UniqueItemName::HoneSundan),
            BaseItem::Lance => Some(UniqueItemName::SpireOfHonor),
            BaseItem::LochaberAxe => Some(UniqueItemName::TheMeatScraper),
            BaseItem::Bill => Some(UniqueItemName::BlackleachBlade),
            BaseItem::BattleScythe => Some(UniqueItemName::AthenasWrath),
            BaseItem::Partizan => Some(UniqueItemName::PierreTombaleCouant),
            BaseItem::BecdeCorbin => Some(UniqueItemName::HusoldalEvo),
            BaseItem::GrimScythe => Some(UniqueItemName::GrimsBurningDead),
            BaseItem::JoStaff => Some(UniqueItemName::Razorswitch),
            BaseItem::Quarterstaff => Some(UniqueItemName::Ribcracker),
            BaseItem::CedarStaff => Some(UniqueItemName::ChromaticIre),
            BaseItem::GothicStaff => Some(UniqueItemName::Warpspear),
            BaseItem::RuneStaff => Some(UniqueItemName::Skullcollector),
            BaseItem::EdgeBow => Some(UniqueItemName::Skystrike),
            BaseItem::RazorBow => Some(UniqueItemName::Riphook),
            BaseItem::CedarBow => Some(UniqueItemName::KukoShakaku),
            BaseItem::DoubleBow => Some(UniqueItemName::Endlesshail),
            BaseItem::ShortSiegeBow => Some(UniqueItemName::WhichwildString),
            BaseItem::LargeSiegeBow => Some(UniqueItemName::Cliffkiller),
            BaseItem::RuneBow => Some(UniqueItemName::Magewrath),
            BaseItem::GothicBow => Some(UniqueItemName::GodstrikeArch),
            BaseItem::Arbalest => Some(UniqueItemName::LangerBriser),
            BaseItem::SiegeCrossbow => Some(UniqueItemName::PusSpiter),
            BaseItem::Ballista => Some(UniqueItemName::BurizaDoKyanon),
            BaseItem::ChuKoNu => Some(UniqueItemName::DemonMachine),
            BaseItem::WarHat => Some(UniqueItemName::PeasentCrown),
            BaseItem::Sallet => Some(UniqueItemName::Rockstopper),
            BaseItem::Casque => Some(UniqueItemName::Stealskull),
            BaseItem::Basinet => Some(UniqueItemName::DarksightHelm),
            BaseItem::WingedHelm => Some(UniqueItemName::ValkiryWing),
            BaseItem::GrandCrown => Some(UniqueItemName::CrownOfThieves),
            BaseItem::DeathMask => Some(UniqueItemName::BlackhornsFace),
            BaseItem::GrimHelm => Some(UniqueItemName::Vampiregaze),
            BaseItem::GhostArmor => Some(UniqueItemName::TheSpiritShroud),
            BaseItem::SerpentskinArmor => Some(UniqueItemName::SkinOfTheVipermagi),
            BaseItem::DemonhideArmor => Some(UniqueItemName::SkinOfTheFlayerdOne),
            BaseItem::TrellisedArmor => Some(UniqueItemName::Ironpelt),
            BaseItem::LinkedMail => Some(UniqueItemName::Spiritforge),
            BaseItem::TigulatedMail => Some(UniqueItemName::CrowCaw),
            BaseItem::MeshArmor => Some(UniqueItemName::Shaftstop),
            BaseItem::Cuirass => Some(UniqueItemName::DurielsShell),
            BaseItem::RussetArmor => Some(UniqueItemName::SkulldersIre),
            BaseItem::TemplarCoat => Some(UniqueItemName::GuardianAngel),
            BaseItem::SharktoothArmor => Some(UniqueItemName::Toothrow),
            BaseItem::EmbossedPlate => Some(UniqueItemName::AtmasWail),
            BaseItem::ChaosArmor => Some(UniqueItemName::BlackHades),
            BaseItem::OrnatePlate => Some(UniqueItemName::Corpsemourn),
            BaseItem::MagePlate => Some(UniqueItemName::QueHegansWisdon),
            BaseItem::Defender => Some(UniqueItemName::Visceratuant),
            BaseItem::RoundShield => Some(UniqueItemName::MosersBlessedCircle),
            BaseItem::Scutum => Some(UniqueItemName::Stormchaser),
            BaseItem::DragonShield => Some(UniqueItemName::TiamatsRebuke),
            BaseItem::Pavise => Some(UniqueItemName::KerkesSanctuary),
            BaseItem::AncientShield => Some(UniqueItemName::RadimantsSphere),
            BaseItem::GrimShield => Some(UniqueItemName::LidlessWall),
            BaseItem::BarbedShield => Some(UniqueItemName::LanceGuard),
            BaseItem::DemonhideGloves => Some(UniqueItemName::VenomGrip),
            BaseItem::SharkskinGloves => Some(UniqueItemName::Gravepalm),
            BaseItem::HeavyBracers => Some(UniqueItemName::Ghoulhide),
            BaseItem::BattleGauntlets => Some(UniqueItemName::Lavagout),
            BaseItem::WarGauntlets => Some(UniqueItemName::Hellmouth),
            BaseItem::DemonhideBoots => Some(UniqueItemName::Infernostride),
            BaseItem::SharkskinBoots => Some(UniqueItemName::Waterwalk),
            BaseItem::MeshBoots => Some(UniqueItemName::Silkweave),
            BaseItem::BattleBoots => Some(UniqueItemName::Wartraveler),
            BaseItem::WarBoots => Some(UniqueItemName::Gorerider),
            BaseItem::DemonhideSash => Some(UniqueItemName::StringOfEars),
            BaseItem::SharkskinBelt => Some(UniqueItemName::Razortail),
            BaseItem::MeshBelt => Some(UniqueItemName::Gloomstrap),
            BaseItem::BattleBelt => Some(UniqueItemName::Snowclash),
            BaseItem::WarBelt => Some(UniqueItemName::ThudergodsVigor),
            BaseItem::Shako => Some(UniqueItemName::HarlequinCrest),
            BaseItem::WireFleece => Some(UniqueItemName::TheGladiatorsBane),
            BaseItem::BalrogSkin => Some(UniqueItemName::ArkainesValor),
            BaseItem::Luna => Some(UniqueItemName::BlackoakShield),
            BaseItem::Monarch => Some(UniqueItemName::Stormshield),
            BaseItem::Decapitator => Some(UniqueItemName::Hellslayer),
            BaseItem::ChampionAxe => Some(UniqueItemName::MesserschmidtsReaver),
            BaseItem::DevilStar => Some(UniqueItemName::BaranarsStar),
            BaseItem::ChampionSword => Some(UniqueItemName::Doombringer),
            BaseItem::ColossusBlade => Some(UniqueItemName::TheGrandfather),
            BaseItem::BoneKnife => Some(UniqueItemName::Wizardspike),
            BaseItem::GiantThresher => Some(UniqueItemName::Stormspire),
            BaseItem::CrusaderBow => Some(UniqueItemName::Eaglehorn),
            BaseItem::HydraBow => Some(UniqueItemName::Windforce),
            BaseItem::SlayerGuard => Some(UniqueItemName::ArreatsFace),
            BaseItem::HierophantTrophy => Some(UniqueItemName::Homunculus),
            BaseItem::CeremonialJavelin => Some(UniqueItemName::TitansRevenge),
            BaseItem::CeremonialBow => Some(UniqueItemName::LycandersAim),
            BaseItem::CeremonialPike => Some(UniqueItemName::LycandersFlank),
            BaseItem::SwirlingCrystal => Some(UniqueItemName::TheOculus),
            BaseItem::GildedShield => Some(UniqueItemName::HeraldOfZakarum),
            BaseItem::GreaterTalons => Some(UniqueItemName::Cutthroat1),
            BaseItem::TotemicMask => Some(UniqueItemName::JalalsMane),
            BaseItem::Francisca => Some(UniqueItemName::TheScalper),
            BaseItem::ElegantBlade => Some(UniqueItemName::Bloodmoon),
            BaseItem::Ataghan => Some(UniqueItemName::Djinnslayer),
            BaseItem::BattleDart => Some(UniqueItemName::Deathbit),
            BaseItem::WingedKnife => Some(UniqueItemName::Warshrike),
            BaseItem::DemonCrossbow => Some(UniqueItemName::Gutsiphon),
            BaseItem::Tomahawk => Some(UniqueItemName::Razoredge),
            BaseItem::TyrantClub => Some(UniqueItemName::Demonlimb),
            BaseItem::CrypticAxe => Some(UniqueItemName::TombReaver),
            BaseItem::UnearthedWand => Some(UniqueItemName::DeathssWeb),
            BaseItem::FangedKnife => Some(UniqueItemName::Fleshripper),
            BaseItem::WristSword => Some(UniqueItemName::Jadetalon),
            BaseItem::MyrmidonGreaves => Some(UniqueItemName::Shadowdancer),
            BaseItem::BloodSpirit => Some(UniqueItemName::Cerebus),
            BaseItem::Vambraces => Some(UniqueItemName::Souldrain),
            BaseItem::EttinAxe => Some(UniqueItemName::Runemaster),
            BaseItem::BerserkerAxe => Some(UniqueItemName::Deathcleaver),
            BaseItem::GloriousAxe => Some(UniqueItemName::ExecutionersJustice),
            BaseItem::MatriarchalSpear => Some(UniqueItemName::Stoneraven),
            BaseItem::KrakenShell => Some(UniqueItemName::Leviathan),
            BaseItem::WingedHarpoon => Some(UniqueItemName::GargoylesBite),
            BaseItem::WingedAxe => Some(UniqueItemName::Lacerator),
            BaseItem::ArchonStaff => Some(UniqueItemName::MangSongsLesson),
            BaseItem::Mancatcher => Some(UniqueItemName::Viperfork),
            BaseItem::SilverEdgedAxe => Some(UniqueItemName::EtherealEdge),
            BaseItem::DestroyerHelm => Some(UniqueItemName::DemonhornsEdge),
            BaseItem::Thresher => Some(UniqueItemName::TheReapersToll),
            BaseItem::EarthSpirit => Some(UniqueItemName::Spiritkeeper),
            BaseItem::ColossusCrossbow => Some(UniqueItemName::Hellrack),
            BaseItem::SacredRondache => Some(UniqueItemName::AlmaNegra),
            BaseItem::BloodlordSkull => Some(UniqueItemName::DarkforgeSpawn),
            BaseItem::WardBow => Some(UniqueItemName::Widowmaker),
            BaseItem::MatriarchalBow => Some(UniqueItemName::BloodravensCharge),
            BaseItem::LegendSpike => Some(UniqueItemName::Ghostflame),
            BaseItem::BattleCestus => Some(UniqueItemName::Shadowkiller),
            BaseItem::FlyingAxe => Some(UniqueItemName::Gimmershred),
            BaseItem::Diadem => Some(UniqueItemName::GriffonsEye),
            BaseItem::OgreMaul => Some(UniqueItemName::Windhammer),
            BaseItem::MatriarchalJavelin => Some(UniqueItemName::Thunderstroke),
            BaseItem::BalrogSpear => Some(UniqueItemName::DemonsArch),
            BaseItem::SuccubusSkull => Some(UniqueItemName::Boneflame),
            BaseItem::WarPike => Some(UniqueItemName::Steelpillar),
            BaseItem::Corona => Some(UniqueItemName::CrownOfAges),
            BaseItem::Demonhead => Some(UniqueItemName::AndarielsVisage),
            BaseItem::ZakarumShield => Some(UniqueItemName::Dragonscale),
            BaseItem::ShadowPlate => Some(UniqueItemName::SteelCarapice),
            BaseItem::Aegis => Some(UniqueItemName::MedusasGaze),
            BaseItem::SkySpirit => Some(UniqueItemName::Ravenlore),
            BaseItem::LichWand => Some(UniqueItemName::Boneshade),
            BaseItem::BalrogBlade => Some(UniqueItemName::Flamebellow),
            BaseItem::DimensionalShard => Some(UniqueItemName::Fathom),
            BaseItem::FuryVisor => Some(UniqueItemName::Wolfhowl),
            BaseItem::Ward => Some(UniqueItemName::SpiritWard),
            BaseItem::Tiara => Some(UniqueItemName::KirasGuardian),
            BaseItem::DuskShroud => Some(UniqueItemName::OrmusRobes),
            BaseItem::GrandCharm => Some(UniqueItemName::GheedsFortune),
            BaseItem::ConquerorCrown => Some(UniqueItemName::HalaberdsReign),
            BaseItem::BladeBarrier => Some(UniqueItemName::SpikeThorn),
            BaseItem::VampireboneGloves => Some(UniqueItemName::DraculsGrasp),
            BaseItem::CrypticSword => Some(UniqueItemName::Frostwind),
            BaseItem::EldritchOrb => Some(UniqueItemName::Eschutastemper),
            BaseItem::FeralClaws => Some(UniqueItemName::FirelizardsTalons),
            BaseItem::ScarabshellBoots => Some(UniqueItemName::SandstormTrek),
            BaseItem::BoneweaveBoots => Some(UniqueItemName::Marrowwalk),
            BaseItem::SpiderwebSash => Some(UniqueItemName::ArachnidMesh),
            BaseItem::VampirefangBelt => Some(UniqueItemName::NosferatusCoil),
            BaseItem::MithrilCoil => Some(UniqueItemName::VerdugosHeartyCord),
            BaseItem::BoneVisage => Some(UniqueItemName::Giantskull),
            BaseItem::Caduceus => Some(UniqueItemName::Ironward),
            BaseItem::SmallCharm => Some(UniqueItemName::Annihilus),
            BaseItem::HyperionSpear => Some(UniqueItemName::AriocsNeedle),
            BaseItem::WarSpike => Some(UniqueItemName::Cranebeak),
            BaseItem::Truncheon => Some(UniqueItemName::NordsTenderizer),
            BaseItem::GhostGlaive => Some(UniqueItemName::Wraithflight),
            BaseItem::OgreAxe => Some(UniqueItemName::Bonehew),
            BaseItem::ElderStaff => Some(UniqueItemName::OndalsWisdom),
            BaseItem::TrollNest => Some(UniqueItemName::HeadhuntersGlory),
            BaseItem::OgreGauntlets => Some(UniqueItemName::Steelrend),
            BaseItem::LargeCharm => Some(UniqueItemName::HellfireTorch),
            _ => None,
        }
    }

    pub fn has_flag(&self, flag: ItemFlag) -> bool {
        self.flags & (flag as u32) > 0
    }

    #[allow(unused)]
    pub fn is_identified(&self) -> bool {
        self.has_flag(ItemFlag::Identified)
    }

    pub fn is_ethereal(&self) -> bool {
        self.has_flag(ItemFlag::Ethereal)
    }

    pub fn is_rune(&self) -> bool {
        matches!(
            self.txt_file_no,
            BaseItem::ElRune
                | BaseItem::EldRune
                | BaseItem::TirRune
                | BaseItem::NefRune
                | BaseItem::EthRune
                | BaseItem::IthRune
                | BaseItem::TalRune
                | BaseItem::RalRune
                | BaseItem::OrtRune
                | BaseItem::ThulRune
                | BaseItem::AmnRune
                | BaseItem::SolRune
                | BaseItem::ShaelRune
                | BaseItem::DolRune
                | BaseItem::HelRune
                | BaseItem::IoRune
                | BaseItem::LumRune
                | BaseItem::KoRune
                | BaseItem::FalRune
                | BaseItem::LemRune
                | BaseItem::PulRune
                | BaseItem::UmRune
                | BaseItem::MalRune
                | BaseItem::IstRune
                | BaseItem::GulRune
                | BaseItem::VexRune
                | BaseItem::OhmRune
                | BaseItem::LoRune
                | BaseItem::SurRune
                | BaseItem::BerRune
                | BaseItem::JahRune
                | BaseItem::ChamRune
                | BaseItem::ZodRune
        )
    }

    pub fn is_key(&self) -> bool {
        matches!(self.txt_file_no, BaseItem::KeyOfTerror | BaseItem::KeyOfHate | BaseItem::KeyOfDestruction)
    }

    pub fn is_essence(&self) -> bool {
        matches!(
            self.txt_file_no,
            BaseItem::TwistedEssenceOfSuffering
                | BaseItem::ChargedEssenceOfHatred
                | BaseItem::BurningEssenceOfTerror
                | BaseItem::FesteringEssenceOfDestruction
        )
    }
}

#[allow(unused)]
#[derive(FromPrimitive, Debug, Clone, Default, Hash, PartialEq, Eq, EnumString)]
pub enum Quality {
    Inferior = 1,
    Normal,
    Superior,
    Magic,
    Set,
    Rare,
    Unique,
    Crafted,
    Tempered,
    #[default]
    Unknown,
}

#[derive(FromPrimitive, Debug, Clone, Default, Hash, PartialEq, Eq)]
pub enum InvPage {
    Inventory = 0,
    Equipped = 1,
    Trade = 2,
    Cube = 3,
    Stash = 4,
    Belt = 5,
    #[default]
    Null = 255,
}

#[derive(FromPrimitive, Debug, Clone, Default, Hash, PartialEq, Eq)]
pub enum StashType {
    Body = 0,
    Personal = 1,
    Shared1 = 2,
    Shared2 = 3,
    Shared3 = 4,
    Belt = 5,
    #[default]
    Unknown,
}

#[derive(FromPrimitive, Debug, Clone, Default, Hash, PartialEq, Eq)]
pub enum BodyLocation {
    NotEquipped,
    Helm,
    Amulet,
    BodyArmor,
    RightHand,
    LeftHand,
    RightRing,
    LeftRing,
    Belt,
    Boots,
    Gloves,
    RightHandonSwitch,
    LeftHandonSwitch,
    #[default]
    Unknown,
}

#[derive(FromPrimitive, Debug, Clone, Default, Hash, PartialEq, Eq)]
pub enum ItemMode {
    Stored,
    Equipped,
    InBelt,
    OnGround,
    OnCursor,
    Dropping,
    Socketed,
    #[default]
    Unknown,
}

#[derive(FromPrimitive, Debug, Clone, Default, Hash, PartialEq, Eq)]
pub enum ItemTier {
    Normal,
    Exceptional,
    Elite,
    #[default]
    NotApplicable,
}

#[derive(FromPrimitive, Debug, Clone, Default, Hash, PartialEq, Eq)]
pub enum StashTab {
    #[default]
    None,
    Personal,
    Shared1,
    Shared2,
    Shared3,
}

#[allow(dead_code)]
pub enum ItemFlag {
    Newitem = 0x00000001,
    Target = 0x00000002,
    Targeting = 0x00000004,
    Deleted = 0x00000008,
    Identified = 0x00000010,
    Quantity = 0x00000020,
    Switchin = 0x00000040,
    Switchout = 0x00000080,
    Broken = 0x00000100,
    Repaired = 0x00000200,
    Unk1 = 0x00000400,
    Socketed = 0x00000800,
    Nosell = 0x00001000,
    Instore = 0x00002000,
    Noequip = 0x00004000,
    Named = 0x00008000,
    IsEar = 0x00010000,
    Startitem = 0x00020000,
    Unk2 = 0x00040000,
    Init = 0x00080000,
    Unk3 = 0x00100000,
    Compactsave = 0x00200000,
    Ethereal = 0x00400000,
    Justsaved = 0x00800000,
    Personalized = 0x01000000,
    Lowquality = 0x02000000,
    Runeword = 0x04000000,
    Item = 0x08000000,
}

#[derive(Default, Copy, Clone, PartialEq, Eq, Debug, FromPrimitive, PartialOrd, Ord, Hash, EnumString, Display)]
pub enum BaseItem {
    HandAxe = 0,
    Axe,
    DoubleAxe,
    MilitaryPick,
    WarAxe,
    LargeAxe,
    BroadAxe,
    BattleAxe,
    GreatAxe,
    GiantAxe,
    Wand,
    YewWand,
    BoneWand,
    GrimWand,
    Club,
    Scepter,
    GrandScepter,
    WarScepter,
    SpikedClub,
    Mace,
    MorningStar,
    Flail,
    WarHammer,
    Maul,
    GreatMaul,
    ShortSword,
    Scimitar,
    Sabre,
    Falchion,
    CrystalSword,
    BroadSword,
    LongSword,
    WarSword,
    TwoHandedSword,
    Claymore,
    GiantSword,
    BastardSword,
    Flamberge,
    GreatSword,
    Dagger,
    Dirk,
    Kris,
    Blade,
    ThrowingKnife,
    ThrowingAxe,
    BalancedKnife,
    BalancedAxe,
    Javelin,
    Pilum,
    ShortSpear,
    Glaive,
    ThrowingSpear,
    Spear,
    Trident,
    Brandistock,
    Spetum,
    Pike,
    Bardiche,
    Voulge,
    Scythe,
    Poleaxe,
    Halberd,
    WarScythe,
    ShortStaff,
    LongStaff,
    GnarledStaff,
    BattleStaff,
    WarStaff,
    ShortBow,
    HuntersBow,
    LongBow,
    CompositeBow,
    ShortBattleBow,
    LongBattleBow,
    ShortWarBow,
    LongWarBow,
    LightCrossbow,
    Crossbow,
    HeavyCrossbow,
    RepeatingCrossbow,
    RancidGasPotion,
    OilPotion,
    ChokingGasPotion,
    ExplodingPotion,
    StranglingGasPotion,
    FulminatingPotion,
    DecoyGidbinn,
    TheGidbinn,
    WirtsLeg,
    HoradricMalus,
    HellforgeHammer,
    HoradricStaff,
    StaffOfKings,
    Hatchet,
    Cleaver,
    TwinAxe,
    Crowbill,
    Naga,
    MilitaryAxe,
    BeardedAxe,
    Tabar,
    GothicAxe,
    AncientAxe,
    BurntWand,
    PetrifiedWand,
    TombWand,
    GraveWand,
    Cudgel,
    RuneScepter,
    HolyWaterSprinkler,
    DivineScepter,
    BarbedClub,
    FlangedMace,
    JaggedStar,
    Knout,
    BattleHammer,
    WarClub,
    MarteldeFer,
    Gladius,
    Cutlass,
    Shamshir,
    Tulwar,
    DimensionalBlade,
    BattleSword,
    RuneSword,
    AncientSword,
    Espandon,
    DacianFalx,
    TuskSword,
    GothicSword,
    Zweihander,
    ExecutionerSword,
    Poignard,
    Rondel,
    Cinquedeas,
    Stilleto,
    BattleDart,
    Francisca,
    WarDart,
    Hurlbat,
    WarJavelin,
    GreatPilum,
    Simbilan,
    Spiculum,
    Harpoon,
    WarSpear,
    Fuscina,
    WarFork,
    Yari,
    Lance,
    LochaberAxe,
    Bill,
    BattleScythe,
    Partizan,
    BecdeCorbin,
    GrimScythe,
    JoStaff,
    Quarterstaff,
    CedarStaff,
    GothicStaff,
    RuneStaff,
    EdgeBow,
    RazorBow,
    CedarBow,
    DoubleBow,
    ShortSiegeBow,
    LargeSiegeBow,
    RuneBow,
    GothicBow,
    Arbalest,
    SiegeCrossbow,
    Ballista,
    ChuKoNu,
    KhalimsFlail,
    KhalimsWill,
    Katar,
    WristBlade,
    HatchetHands,
    Cestus,
    Claws,
    BladeTalons,
    ScissorsKatar,
    Quhab,
    WristSpike,
    Fascia,
    HandScythe,
    GreaterClaws,
    GreaterTalons,
    ScissorsQuhab,
    Suwayyah,
    WristSword,
    WarFist,
    BattleCestus,
    FeralClaws,
    RunicTalons,
    ScissorsSuwayyah,
    Tomahawk,
    SmallCrescent,
    EttinAxe,
    WarSpike,
    BerserkerAxe,
    FeralAxe,
    SilverEdgedAxe,
    Decapitator,
    ChampionAxe,
    GloriousAxe,
    PolishedWand,
    GhostWand,
    LichWand,
    UnearthedWand,
    Truncheon,
    MightyScepter,
    SeraphRod,
    Caduceus,
    TyrantClub,
    ReinforcedMace,
    DevilStar,
    Scourge,
    LegendaryMallet,
    OgreMaul,
    ThunderMaul,
    Falcata,
    Ataghan,
    ElegantBlade,
    HydraEdge,
    PhaseBlade,
    ConquestSword,
    CrypticSword,
    MythicalSword,
    LegendSword,
    HighlandBlade,
    BalrogBlade,
    ChampionSword,
    ColossalSword,
    ColossusBlade,
    BoneKnife,
    MithrilPoint,
    FangedKnife,
    LegendSpike,
    FlyingKnife,
    FlyingAxe,
    WingedKnife,
    WingedAxe,
    HyperionJavelin,
    StygianPilum,
    BalrogSpear,
    GhostGlaive,
    WingedHarpoon,
    HyperionSpear,
    StygianPike,
    Mancatcher,
    GhostSpear,
    WarPike,
    OgreAxe,
    ColossusVoulge,
    Thresher,
    CrypticAxe,
    GreatPoleaxe,
    GiantThresher,
    WalkingStick,
    Stalagmite,
    ElderStaff,
    Shillelagh,
    ArchonStaff,
    SpiderBow,
    BladeBow,
    ShadowBow,
    GreatBow,
    DiamondBow,
    CrusaderBow,
    WardBow,
    HydraBow,
    PelletBow,
    GorgonCrossbow,
    ColossusCrossbow,
    DemonCrossbow,
    EagleOrb,
    SacredGlobe,
    SmokedSphere,
    ClaspedOrb,
    JaredsStone,
    StagBow,
    ReflexBow,
    MaidenSpear,
    MaidenPike,
    MaidenJavelin,
    GlowingOrb,
    CrystallineGlobe,
    CloudySphere,
    SparklingBall,
    SwirlingCrystal,
    AshwoodBow,
    CeremonialBow,
    CeremonialSpear,
    CeremonialPike,
    CeremonialJavelin,
    HeavenlyStone,
    EldritchOrb,
    DemonHeart,
    VortexOrb,
    DimensionalShard,
    MatriarchalBow,
    GrandMatronBow,
    MatriarchalSpear,
    MatriarchalPike,
    MatriarchalJavelin,
    Cap,
    SkullCap,
    Helm,
    FullHelm,
    GreatHelm,
    Crown,
    Mask,
    QuiltedArmor,
    LeatherArmor,
    HardLeatherArmor,
    StuddedLeather,
    RingMail,
    ScaleMail,
    ChainMail,
    BreastPlate,
    SplintMail,
    PlateMail,
    FieldPlate,
    GothicPlate,
    FullPlateMail,
    AncientArmor,
    LightPlate,
    Buckler,
    SmallShield,
    LargeShield,
    KiteShield,
    TowerShield,
    GothicShield,
    LeatherGloves,
    HeavyGloves,
    ChainGloves,
    LightGauntlets,
    Gauntlets,
    Boots,
    HeavyBoots,
    ChainBoots,
    LightPlatedBoots,
    Greaves,
    Sash,
    LightBelt,
    Belt,
    HeavyBelt,
    PlatedBelt,
    BoneHelm,
    BoneShield,
    SpikedShield,
    WarHat,
    Sallet,
    Casque,
    Basinet,
    WingedHelm,
    GrandCrown,
    DeathMask,
    GhostArmor,
    SerpentskinArmor,
    DemonhideArmor,
    TrellisedArmor,
    LinkedMail,
    TigulatedMail,
    MeshArmor,
    Cuirass,
    RussetArmor,
    TemplarCoat,
    SharktoothArmor,
    EmbossedPlate,
    ChaosArmor,
    OrnatePlate,
    MagePlate,
    Defender,
    RoundShield,
    Scutum,
    DragonShield,
    Pavise,
    AncientShield,
    DemonhideGloves,
    SharkskinGloves,
    HeavyBracers,
    BattleGauntlets,
    WarGauntlets,
    DemonhideBoots,
    SharkskinBoots,
    MeshBoots,
    BattleBoots,
    WarBoots,
    DemonhideSash,
    SharkskinBelt,
    MeshBelt,
    BattleBelt,
    WarBelt,
    GrimHelm,
    GrimShield,
    BarbedShield,
    WolfHead,
    HawkHelm,
    Antlers,
    FalconMask,
    SpiritMask,
    JawboneCap,
    FangedHelm,
    HornedHelm,
    AssaultHelmet,
    AvengerGuard,
    Targe,
    Rondache,
    HeraldicShield,
    AerinShield,
    CrownShield,
    PreservedHead,
    ZombieHead,
    UnravellerHead,
    GargoyleHead,
    DemonHead,
    Circlet,
    Coronet,
    Tiara,
    Diadem,
    Shako,
    Hydraskull,
    Armet,
    GiantConch,
    SpiredHelm,
    Corona,
    Demonhead,
    DuskShroud,
    Wyrmhide,
    ScarabHusk,
    WireFleece,
    DiamondMail,
    LoricatedMail,
    Boneweave,
    GreatHauberk,
    BalrogSkin,
    HellforgePlate,
    KrakenShell,
    LacqueredPlate,
    ShadowPlate,
    SacredArmor,
    ArchonPlate,
    Heater,
    Luna,
    Hyperion,
    Monarch,
    Aegis,
    Ward,
    BrambleMitts,
    VampireboneGloves,
    Vambraces,
    CrusaderGauntlets,
    OgreGauntlets,
    WyrmhideBoots,
    ScarabshellBoots,
    BoneweaveBoots,
    MirroredBoots,
    MyrmidonGreaves,
    SpiderwebSash,
    VampirefangBelt,
    MithrilCoil,
    TrollBelt,
    ColossusGirdle,
    BoneVisage,
    TrollNest,
    BladeBarrier,
    AlphaHelm,
    GriffonHeaddress,
    HuntersGuise,
    SacredFeathers,
    TotemicMask,
    JawboneVisor,
    LionHelm,
    RageMask,
    SavageHelmet,
    SlayerGuard,
    AkaranTarge,
    AkaranRondache,
    ProtectorShield,
    GildedShield,
    RoyalShield,
    MummifiedTrophy,
    FetishTrophy,
    SextonTrophy,
    CantorTrophy,
    HierophantTrophy,
    BloodSpirit,
    SunSpirit,
    EarthSpirit,
    SkySpirit,
    DreamSpirit,
    CarnageHelm,
    FuryVisor,
    DestroyerHelm,
    ConquerorCrown,
    GuardianCrown,
    SacredTarge,
    SacredRondache,
    KurastShield,
    ZakarumShield,
    VortexShield,
    MinionSkull,
    HellspawnSkull,
    OverseerSkull,
    SuccubusSkull,
    BloodlordSkull,
    Elixir,
    HealingPotion2,
    ManaPotion2,
    FullHealingPotion,
    FullManaPotion,
    StaminaPotion,
    AntidotePotion,
    RejuvenationPotion,
    FullRejuvenationPotion,
    ThawingPotion,
    TomeOfTownPortal,
    TomeOfIdentify,
    Amulet,
    AmuletOfTheViper,
    Ring,
    Gold,
    ScrollOfInifuss,
    KeytotheCairnStones,
    Arrows,
    Torch,
    Bolts,
    ScrollOfTownPortal,
    ScrollOfIdentify,
    Heart,
    Brain,
    Jawbone,
    Eye,
    Horn,
    Tail,
    Flag,
    Fang,
    Quill,
    Soul,
    Scalp,
    Spleen,
    Key,
    TheBlackTowerKey,
    PotionOfLife,
    AJadeFigurine,
    TheGoldenBird,
    LamEsensTome,
    HoradricCube,
    HoradricScroll,
    MephistosSoulstone,
    BookOfSkill,
    KhalimsEye,
    KhalimsHeart,
    KhalimsBrain,
    Ear,
    ChippedAmethyst,
    FlawedAmethyst,
    Amethyst,
    FlawlessAmethyst,
    PerfectAmethyst,
    ChippedTopaz,
    FlawedTopaz,
    Topaz,
    FlawlessTopaz,
    PerfectTopaz,
    ChippedSapphire,
    FlawedSapphire,
    Sapphire,
    FlawlessSapphire,
    PerfectSapphire,
    ChippedEmerald,
    FlawedEmerald,
    Emerald,
    FlawlessEmerald,
    PerfectEmerald,
    ChippedRuby,
    FlawedRuby,
    Ruby,
    FlawlessRuby,
    PerfectRuby,
    ChippedDiamond,
    FlawedDiamond,
    Diamond,
    FlawlessDiamond,
    PerfectDiamond,
    MinorHealingPotion,
    LightHealingPotion,
    HealingPotion,
    GreaterHealingPotion,
    SuperHealingPotion,
    MinorManaPotion,
    LightManaPotion,
    ManaPotion,
    GreaterManaPotion,
    SuperManaPotion,
    ChippedSkull,
    FlawedSkull,
    Skull,
    FlawlessSkull,
    PerfectSkull,
    Herb,
    SmallCharm,
    LargeCharm,
    GrandCharm,
    SmallRedPotion,
    LargeRedPotion,
    SmallBluePotion,
    LargeBluePotion,
    ElRune,
    EldRune,
    TirRune,
    NefRune,
    EthRune,
    IthRune,
    TalRune,
    RalRune,
    OrtRune,
    ThulRune,
    AmnRune,
    SolRune,
    ShaelRune,
    DolRune,
    HelRune,
    IoRune,
    LumRune,
    KoRune,
    FalRune,
    LemRune,
    PulRune,
    UmRune,
    MalRune,
    IstRune,
    GulRune,
    VexRune,
    OhmRune,
    LoRune,
    SurRune,
    BerRune,
    JahRune,
    ChamRune,
    ZodRune,
    Jewel,
    MalahsPotion,
    ScrollOfKnowledge,
    ScrollOfResistance,
    KeyOfTerror,
    KeyOfHate,
    KeyOfDestruction,
    DiablosHorn,
    BaalsEye,
    MephistosBrain,
    TokenOfAbsolution,
    TwistedEssenceOfSuffering,
    ChargedEssenceOfHatred,
    BurningEssenceOfTerror,
    FesteringEssenceOfDestruction,
    StandardOfHeroes,
    #[default]
    Unknown,
}

#[derive(FromPrimitive, Debug, Clone, Default, Hash, PartialEq, Eq)]
pub enum UniqueItemName {
    TheGnasher = 0,
    Deathspade,
    Bladebone,
    Mindrend,
    Rakescar,
    FechmarsAxe,
    Goreshovel,
    TheChieftan,
    Brainhew,
    TheHumongous,
    IrosTorch,
    Maelstromwrath,
    Gravenspine,
    UmesLament,
    Felloak,
    KnellStriker,
    Rusthandle,
    Stormeye,
    Stoutnail,
    Crushflange,
    Bloodrise,
    TheGeneralsTanDoLiGa,
    Ironstone,
    Bonesob,
    Steeldriver,
    RixotsKeen,
    BloodCrescent,
    KrintizsSkewer,
    Gleamscythe,
    Azurewrath,
    GriswoldsEdge,
    Hellplague,
    CulwensPoint,
    Shadowfang,
    Soulflay,
    KinemilsAwl,
    Blacktongue,
    Ripsaw,
    ThePatriarch,
    Gull,
    TheDiggler,
    TheJadeTanDo,
    IricesShard,
    TheDragonChang,
    Razortine,
    Bloodthief,
    LanceOfYaggai,
    TheTannrGorerod,
    DimoaksHew,
    Steelgoad,
    SoulHarvest,
    TheBattlebranch,
    Woestave,
    TheGrimReaper,
    BaneAsh,
    SerpentLord,
    LazarusSpire,
    TheSalamander,
    TheIronJangBong,
    Pluckeye,
    Witherstring,
    Rimeraven,
    Piercerib,
    Pullspite,
    Wizendraw,
    Hellclap,
    Blastbark,
    Leadcrow,
    Ichorsting,
    Hellcast,
    Doomspittle,
    WarBonnet,
    Tarnhelm,
    CoifOfGlory,
    Duskdeep,
    Wormskull,
    Howltusk,
    UndeadCrown,
    TheFaceOfHorror,
    Greyform,
    BlinkbatsForm,
    TheCenturion,
    Twitchthroe,
    Darkglow,
    Hawkmail,
    SparkingMail,
    Venomsward,
    Iceblink,
    Boneflesh,
    Rockfleece,
    Rattlecage,
    Goldskin,
    VictorsSilk,
    HeavenlyGarb,
    PeltaLunata,
    UmbralDisk,
    Stormguild,
    WallOfTheEyeless,
    SwordbackHold,
    Steelclash,
    BverritKeep,
    TheWard,
    TheHandOfBroc,
    Bloodfist,
    ChanceGuards,
    Magefist,
    Frostburn,
    Hotspur,
    Gorefoot,
    TreadsOfCthon,
    GoblinToe,
    Tearhaunch,
    LenymsCord,
    Snakecord,
    Nightsmoke,
    Goldwrap,
    Bladebuckle,
    NokozanRelic,
    TheEyeOfEtlich,
    TheMahimOakCurio,
    Nagelring,
    ManaldHeal,
    TheStoneOfJordan,
    AmuletOfTheViper,
    StaffOfKings,
    HoradricStaff,
    HellForgeHammer,
    KhalimFlail,
    SuperKhalimFlail,
    Coldkill,
    ButchersPupil,
    Islestrike,
    PompesWrath,
    GuardianNaga,
    WarlordsTrust,
    Spellsteel,
    Stormrider,
    BoneslayerBlade,
    TheMinataur,
    SuicideBranch,
    CarinShard,
    ArmOfKingLeoric,
    BlackhandKey,
    DarkClanCrusher,
    ZakarumsHand,
    TheFetidSprinkler,
    HandOfBlessedLight,
    Fleshrender,
    SureshrillFrost,
    Moonfall,
    BaezilsVortex,
    Earthshaker,
    BloodtreeStump,
    TheGavelOfPain,
    Bloodletter,
    ColdsteelEye,
    Hexfire,
    BladeOfAliBaba,
    GinthersRift,
    Headstriker,
    PlagueBearer,
    TheAtlantian,
    CrainteVomir,
    BingSzWang,
    TheVileHusk,
    Cloudcrack,
    TodesfaelleFlamme,
    Swordguard,
    Spineripper,
    HeartCarver,
    BlackbogsSharp,
    Stormspike,
    TheImpaler,
    KelpieSnare,
    SoulfeastTine,
    HoneSundan,
    SpireOfHonor,
    TheMeatScraper,
    BlackleachBlade,
    AthenasWrath,
    PierreTombaleCouant,
    HusoldalEvo,
    GrimsBurningDead,
    Razorswitch,
    Ribcracker,
    ChromaticIre,
    Warpspear,
    Skullcollector,
    Skystrike,
    Riphook,
    KukoShakaku,
    Endlesshail,
    WhichwildString,
    Cliffkiller,
    Magewrath,
    GodstrikeArch,
    LangerBriser,
    PusSpiter,
    BurizaDoKyanon,
    DemonMachine,
    Armor,
    PeasentCrown,
    Rockstopper,
    Stealskull,
    DarksightHelm,
    ValkiryWing,
    CrownOfThieves,
    BlackhornsFace,
    Vampiregaze,
    TheSpiritShroud,
    SkinOfTheVipermagi,
    SkinOfTheFlayerdOne,
    Ironpelt,
    Spiritforge,
    CrowCaw,
    Shaftstop,
    DurielsShell,
    SkulldersIre,
    GuardianAngel,
    Toothrow,
    AtmasWail,
    BlackHades,
    Corpsemourn,
    QueHegansWisdon,
    Visceratuant,
    MosersBlessedCircle,
    Stormchaser,
    TiamatsRebuke,
    KerkesSanctuary,
    RadimantsSphere,
    LidlessWall,
    LanceGuard,
    VenomGrip,
    Gravepalm,
    Ghoulhide,
    Lavagout,
    Hellmouth,
    Infernostride,
    Waterwalk,
    Silkweave,
    Wartraveler,
    Gorerider,
    StringOfEars,
    Razortail,
    Gloomstrap,
    Snowclash,
    ThudergodsVigor,
    EliteUniques,
    HarlequinCrest,
    VeilOfSteel,
    TheGladiatorsBane,
    ArkainesValor,
    BlackoakShield,
    Stormshield,
    Hellslayer,
    MesserschmidtsReaver,
    BaranarsStar,
    SchaefersHammer,
    TheCraniumBasher,
    Lightsabre,
    Doombringer,
    TheGrandfather,
    Wizardspike,
    ConstrictingRing,
    Stormspire,
    Eaglehorn,
    Windforce,
    Rings,
    BulKathosWeddingBand,
    TheCatsEye,
    TheRisingSun,
    CrescentMoon,
    MarasKaleidoscope,
    AtmasScarab,
    DwarfStar,
    RavenFrost,
    HighlordsWrath,
    SaracensChance,
    ClassSpecific,
    ArreatsFace,
    Homunculus,
    TitansRevenge,
    LycandersAim,
    LycandersFlank,
    TheOculus,
    HeraldOfZakarum,
    Cutthroat1,
    JalalsMane,
    TheScalper,
    Bloodmoon,
    Djinnslayer,
    Deathbit,
    Warshrike,
    Gutsiphon,
    Razoredge,
    GoreRipper,
    Demonlimb,
    Steelshade,
    TombReaver,
    DeathssWeb,
    NaturesPeace,
    Azurewrath2,
    SeraphsHymn,
    ZakarumsSalvation,
    Fleshripper,
    Odium,
    HorizonsTornado,
    StoneCrusher,
    Jadetalon,
    Shadowdancer,
    Cerebus,
    TyraelsMight,
    Souldrain,
    Runemaster,
    Deathcleaver,
    ExecutionersJustice,
    Stoneraven,
    Leviathan,
    LarzuksChampion,
    Wisp,
    GargoylesBite,
    Lacerator,
    MangSongsLesson,
    Viperfork,
    EtherealEdge,
    DemonhornsEdge,
    TheReapersToll,
    Spiritkeeper,
    Hellrack,
    AlmaNegra,
    DarkforgeSpawn,
    Widowmaker,
    BloodravensCharge,
    Ghostflame,
    Shadowkiller,
    Gimmershred,
    GriffonsEye,
    Windhammer,
    Thunderstroke,
    Giantmaimer,
    DemonsArch,
    Boneflame,
    Steelpillar,
    NightwingsVeil,
    CrownOfAges,
    AndarielsVisage,
    Darkfear,
    Dragonscale,
    SteelCarapice,
    MedusasGaze,
    Ravenlore,
    Boneshade,
    Nethercrow,
    Flamebellow,
    Fathom,
    Wolfhowl,
    SpiritWard,
    KirasGuardian,
    OrmusRobes,
    GheedsFortune,
    Stormlash,
    HalaberdsReign,
    WarrivsWarder,
    SpikeThorn,
    DraculsGrasp,
    Frostwind,
    TemplarsMight,
    Eschutastemper,
    FirelizardsTalons,
    SandstormTrek,
    Marrowwalk,
    HeavensLight,
    MermansSpeed,
    ArachnidMesh,
    NosferatusCoil,
    Metalgrid,
    VerdugosHeartyCord,
    SigurdsStaunch,
    CarrionWind,
    Giantskull,
    Ironward,
    Annihilus,
    AriocsNeedle,
    Cranebeak,
    NordsTenderizer,
    Earthshifter,
    Wraithflight,
    Bonehew,
    OndalsWisdom,
    TheReedeemer,
    HeadhuntersGlory,
    Steelrend,
    RainbowFacetLightning,
    RainbowFacetCold,
    RainbowFacetFire,
    RainbowFacetPsn,
    RainbowFacetLightning2,
    RainbowFacetCold2,
    RainbowFacetFire2,
    RainbowFacetPsn2,
    HellfireTorch,
    ColdRupture,
    FlameRift,
    CrackOfTheHeavens,
    RottingFissure,
    BoneBreak,
    BlackCleft,
    #[default]
    Unknown,
}

#[derive(FromPrimitive, Debug, Clone, Default, Hash, PartialEq, Eq)]
pub enum SetItemName {
    CiverbsWard = 0,
    CiverbsIcon,
    CiverbsCudgel,
    HsarusIronHeel,
    HsarusIronFist,
    HsarusIronStay,
    CleglawsTooth,
    CleglawsClaw,
    CleglawsPincers,
    IrathasCollar,
    IrathasCuff,
    IrathasCoil,
    IrathasCord,
    IsenhartsLightbrand,
    IsenhartsParry,
    IsenhartsCase,
    IsenhartsHorns,
    VidalasBarb,
    VidalasFetlock,
    VidalasAmbush,
    VidalasSnare,
    MilabregasOrb,
    MilabregasRod,
    MilabregasDiadem,
    MilabregasRobe,
    CathansRule,
    CathansMesh,
    CathansVisage,
    CathansSigil,
    CathansSeal,
    TancredsCrowbill,
    TancredsSpine,
    TancredsHobnails,
    TancredsWeird,
    TancredsSkull,
    SigonsGage,
    SigonsVisor,
    SigonsShelter,
    SigonsSabot,
    SigonsWrap,
    SigonsGuard,
    InfernalCranium,
    InfernalTorch,
    InfernalSign,
    BerserkersHeadgear,
    BerserkersHauberk,
    BerserkersHatchet,
    DeathsHand,
    DeathsGuard,
    DeathsTouch,
    AngelicSickle,
    AngelicMantle,
    AngelicHalo,
    AngelicWings,
    ArcticHorn,
    ArcticFurs,
    ArcticBinding,
    ArcticMitts,
    ArcannasSign,
    ArcannasDeathwand,
    ArcannasHead,
    ArcannasFlesh,
    NatalyasTotem,
    NatalyasMark,
    NatalyasShadow,
    NatalyasSoul,
    AldursStonyGaze,
    AldursDeception,
    AldursGauntlet,
    AldursAdvance,
    ImmortalKingsWill,
    ImmortalKingsSoulCage,
    ImmortalKingsDetail,
    ImmortalKingsForge,
    ImmortalKingsPillar,
    ImmortalKingsStoneCrusher,
    TalRashasFireSpunCloth,
    TalRashasAdjudication,
    TalRashasLidlessEye,
    TalRashasHowlingWind,
    TalRashasHoradricCrest,
    GriswoldsValor,
    GriswoldsHeart,
    GriswoldssRedemption,
    GriswoldsHonor,
    TrangOulsGuise,
    TrangOulsScales,
    TrangOulsWing,
    TrangOulsClaws,
    TrangOulsGirth,
    MavinasTrueSight,
    MavinasEmbrace,
    MavinasIcyClutch,
    MavinasTenet,
    MavinasCaster,
    TellingOfBeads,
    LayingOfHands,
    RiteOfPassage,
    SpiritualCustodian,
    Credendum,
    DangoonsTeaching,
    HeavensTaebaek,
    HaemosusAdament,
    OndalsAlmighty,
    GuillaumesFace,
    WilhelmsPride,
    MagnusSkin,
    WihtstansGuard,
    HwaninsSplendor,
    HwaninsRefuge,
    HwaninsSeal,
    HwaninsJustice,
    SazabisCobaltRedeemer,
    SazabisGhostLiberator,
    SazabisMentalSheath,
    BulKathosSacredCharge,
    BulKathosTribalGuardian,
    CowKingsHorns,
    CowKingsHide,
    CowKingsHoofs,
    NajsPuzzler,
    NajsLightPlate,
    NajsCirclet,
    McAuleysParagon,
    McAuleysRiprap,
    McAuleysTaboo,
    McAuleysSuperstition,
    #[default]
    Unknown,
}
