use derivative::Derivative;
use std::collections::HashSet;

use num_derive::FromPrimitive;
use num_traits::FromPrimitive;

use crate::memory::{
    process::D2RInstance,
    structs::{MonsterData, StatsList, Unit},
};

use super::{
    enchants::{get_monster_enchants, MonsterEnchants},
    get_position,
    states::{self, State},
    stats::{read_stats, Immunity, Stat, StatEnum},
};

#[allow(dead_code)]
#[derive(Derivative, Debug, Clone)]
#[derivative(Default)]
pub struct NPCUnit {
    pub unit_id: u32,
    pub txt_file_no: NPC,
    pub mode: NPCMode,
    pub pos_x: f32,
    pub pos_y: f32,
    #[derivative(Default(value = "[State::None; 192]"))]
    pub states: [State; 192],
    pub p_path: u64,
    pub npc_type: NPCType,
    pub monster_flag: MonsterFlag,
    pub monster_enchants: Vec<MonsterEnchants>,
    pub monster_stats: Vec<Stat>,
}

impl NPCUnit {
    pub fn new(d2rprocess: &D2RInstance, unit: Unit) -> Self {
        let txt_file_no: NPC = match NPC::from_u32(unit.txt_file_no) {
            Some(txt_file_no) => txt_file_no,
            None => return NPCUnit::default(),
        };
        let mode = match NPCMode::from_u32(unit.mode) {
            Some(mode) => mode,
            None => return NPCUnit::default(),
        };
        let (pos_x, pos_y) = get_position(d2rprocess, unit);
        let monster_flag: MonsterFlag = Self::get_monster_data(d2rprocess, unit);
        let states = Self::get_states(d2rprocess, unit);
        let monster_stats = Self::get_monster_stats(d2rprocess, unit);
        let monster_enchants = Self::get_monster_enchants(d2rprocess, unit);

        let npc_type = get_type(&txt_file_no);
        NPCUnit {
            unit_id: unit.unit_id,
            txt_file_no,
            mode,
            pos_x,
            pos_y,
            states,
            p_path: unit.p_path,
            npc_type,
            monster_flag,
            monster_enchants,
            monster_stats,
        }
    }

    pub fn get_monster_data(d2rprocess: &D2RInstance, unit: Unit) -> MonsterFlag {
        if unit.p_unit_data == 0 {
            MonsterFlag::None
        } else {
            let npc_data: MonsterData = d2rprocess.read_mem::<MonsterData>(unit.p_unit_data);
            match npc_data.monster_flags {
                10 => MonsterFlag::SuperUnique,
                8 => MonsterFlag::Unique,
                12 => MonsterFlag::Champion,
                16 => MonsterFlag::Minion,
                _ => MonsterFlag::None,
            }
        }
    }

    pub fn get_monster_enchants(d2rprocess: &D2RInstance, unit: Unit) -> Vec<MonsterEnchants> {
        if unit.p_unit_data == 0 {
            return vec![];
        } else {
            let npc_data: MonsterData = d2rprocess.read_mem::<MonsterData>(unit.p_unit_data);
            return get_monster_enchants(&npc_data);
        }
    }

    pub fn get_monster_stats(d2rprocess: &D2RInstance, unit: Unit) -> Vec<Stat> {
        if unit.p_stats_list_ex == 0 {
            vec![]
        } else {
            read_stats(d2rprocess, &unit)
        }
    }

    pub fn get_states(d2rprocess: &D2RInstance, unit: Unit) -> [State; 192] {
        if unit.p_stats_list_ex == 0 {
            [State::None; 192]
        } else {
            let stat_list: StatsList = d2rprocess.read_mem::<StatsList>(unit.p_stats_list_ex);
            let state_flags = stat_list.state_flags;
            states::parse_state_flags(state_flags)
        }
    }

    #[allow(unused)]
    pub fn has_state(&self, state: State) -> bool {
        self.states[state as usize] == state
    }

    pub fn get_health(&self) -> Option<(u16, u16)> {
        let health: Vec<&Stat> = self
            .monster_stats
            .iter()
            .filter(|s: &&Stat| s.stat == StatEnum::Life)
            .collect();
        let max_health: Vec<&Stat> = self
            .monster_stats
            .iter()
            .filter(|s: &&Stat| s.stat == StatEnum::MaxLife)
            .collect();
        let health_values: u16 = match health
            .iter()
            .map(|s| ((s.value2 as u16) << 8) ^ (s.value as u8) as u16)
            .max()
        {
            Some(hp) => hp,
            None => 0,
        };
        let max_health_values: u16 = match max_health
            .iter()
            .map(|s| ((s.value2 as u16) << 8) ^ (s.value as u8) as u16)
            .max()
        {
            Some(hp) => hp,
            None => 0,
        };
        Some((health_values, max_health_values))
    }

    pub fn get_immunities(&self) -> HashSet<Immunity> {
        let mut immunities: HashSet<Immunity> = HashSet::new();
        self.monster_stats.iter().for_each(|stat| match stat.stat {
            StatEnum::DamageReduced => {
                if stat.value >= 100 {
                    immunities.insert(Immunity::Physical);
                }
            }
            StatEnum::MagicResist => {
                if stat.value >= 100 {
                    immunities.insert(Immunity::Magic);
                }
            }
            StatEnum::FireResist => {
                if stat.value >= 100 {
                    immunities.insert(Immunity::Fire);
                }
            }
            StatEnum::LightningResist => {
                if stat.value >= 100 {
                    immunities.insert(Immunity::Lightning);
                }
            }
            StatEnum::ColdResist => {
                if stat.value >= 100 {
                    immunities.insert(Immunity::Cold);
                }
            }
            StatEnum::PoisonResist => {
                if stat.value >= 100 {
                    immunities.insert(Immunity::Poison);
                }
            }
            _ => (),
        });
        immunities
    }
}

#[allow(dead_code)]
#[derive(Clone, Debug, Default)]
pub enum NPCType {
    Monster,
    Town,
    Boss,
    OtherPlayer,
    Pet,
    #[default]
    Dummy,
}

#[allow(dead_code)]
#[derive(Clone, Debug, Default)]
pub enum MonsterFlag {
    #[default]
    None,
    SuperUnique,
    Champion,
    Unique,
    Minion,
    Possessed,
    Ghostly,
    Multishot,
}

#[derive(FromPrimitive, Copy, Debug, Clone, PartialEq, PartialOrd, Default)]
pub enum NPCMode {
    Death,
    Neutral,
    Walk,
    Gethit,
    Attack1,
    Attack2,
    Block,
    Cast,
    Skill1,
    Skill2,
    Skill3,
    Skill4,
    Dead,
    Knockback,
    Sequence,
    Run,
    #[default]
    Unknown,
}

#[repr(u32)]
#[derive(FromPrimitive, Debug, Clone, Default)]
pub enum NPC {
    Skeleton,
    Returned,
    BoneWarrior,
    BurningDead,
    Horror,
    Zombie,
    HungryDead,
    Ghoul,
    DrownedCarcass,
    PlagueBearer,
    Afflicted,
    Tainted,
    Misshapen,
    Disfigured,
    Damned,
    FoulCrow,
    BloodHawk,
    BlackRaptor,
    CloudStalker,
    Fallen,
    Carver,
    Devilkin,
    DarkOne,
    WarpedFallen,
    Brute,
    Yeti,
    Crusher,
    WailingBeast,
    GargantuanBeast,
    SandRaider,
    Marauder,
    Invader,
    Infidel,
    Assailant,
    Gorgon,
    Gorgon2,
    Gorgon3,
    Gorgon4,
    Ghost,
    Wraith,
    Specter,
    Apparition,
    DarkShape,
    DarkHunter,
    VileHunter,
    DarkStalker,
    BlackRogue,
    FleshHunter,
    DuneBeast,
    RockDweller,
    JungleHunter,
    DoomApe,
    TempleGuard,
    MoonClan,
    NightClan,
    BloodClan,
    HellClan,
    DeathClan,
    FallenShaman,
    CarverShaman,
    DevilkinShaman,
    DarkShaman,
    WarpedShaman,
    QuillRat,
    SpikeFiend,
    ThornBeast,
    RazorSpine,
    JungleUrchin,
    SandMaggot,
    RockWorm,
    Devourer,
    GiantLamprey,
    WorldKiller,
    TombViper,
    ClawViper,
    Salamander,
    PitViper,
    SerpentMagus,
    SandLeaper,
    CaveLeaper,
    TombCreeper,
    TreeLurker,
    RazorPitDemon,
    Huntress,
    SaberCat,
    NightTiger,
    HellCat,
    Itchies,
    BlackLocusts,
    PlagueBugs,
    HellSwarm,
    DungSoldier,
    SandWarrior,
    Scarab,
    SteelWeevil,
    AlbinoRoach,
    DriedCorpse,
    Decayed,
    Embalmed,
    PreservedDead,
    Cadaver,
    HollowOne,
    Guardian,
    Unraveler,
    HoradrimAncient,
    BaalSubjectMummy,
    ChaosHorde,
    ChaosHorde2,
    ChaosHorde3,
    ChaosHorde4,
    CarrionBird,
    UndeadScavenger,
    HellBuzzard,
    WingedNightmare,
    Sucker,
    Feeder,
    BloodHook,
    BloodWing,
    Gloam,
    SwampGhost,
    BurningSoul,
    BlackSoul,
    Arach,
    SandFisher,
    PoisonSpinner,
    FlameSpider,
    SpiderMagus,
    ThornedHulk,
    BrambleHulk,
    Thrasher,
    Spikefist,
    GhoulLord,
    NightLord,
    DarkLord,
    BloodLord,
    Banished,
    DesertWing,
    Fiend,
    Gloombat,
    BloodDiver,
    DarkFamiliar,
    RatMan,
    Fetish,
    Flayer,
    SoulKiller,
    StygianDoll,
    DeckardCain,
    Gheed,
    Akara,
    Chicken,
    Kashya,
    Rat,
    Rogue,
    HellMeteor,
    Charsi,
    Warriv,
    Andariel,
    Bird,
    Bird2,
    Bat,
    DarkRanger,
    VileArcher,
    DarkArcher,
    BlackArcher,
    FleshArcher,
    DarkSpearwoman,
    VileLancer,
    DarkLancer,
    BlackLancer,
    FleshLancer,
    SkeletonArcher,
    ReturnedArcher,
    BoneArcher,
    BurningDeadArcher,
    HorrorArcher,
    Warriv2,
    Atma,
    Drognan,
    Fara,
    Cow,
    SandMaggotYoung,
    RockWormYoung,
    DevourerYoung,
    GiantLampreyYoung,
    WorldKillerYoung,
    Camel,
    Blunderbore,
    Gorbelly,
    Mauler,
    Urdar,
    SandMaggotEgg,
    RockWormEgg,
    DevourerEgg,
    GiantLampreyEgg,
    WorldKillerEgg,
    Act2Male,
    Act2Female,
    Act2Child,
    Greiz,
    Elzix,
    Geglash,
    Jerhyn,
    Lysander,
    Act2Guard,
    Act2Vendor,
    Act2Vendor2,
    FoulCrowNest,
    BloodHawkNest,
    BlackVultureNest,
    CloudStalkerNest,
    Meshif,
    Duriel,
    UndeadRatMan,
    UndeadFetish,
    UndeadFlayer,
    UndeadSoulKiller,
    UndeadStygianDoll,
    DarkGuard,
    DarkGuard2,
    DarkGuard3,
    DarkGuard4,
    DarkGuard5,
    BloodMage,
    BloodMage2,
    BloodMage3,
    BloodMage4,
    BloodMage5,
    Maggot,
    MummyGenerator,
    Radament,
    FireBeast,
    IceGlobe,
    LightningBeast,
    PoisonOrb,
    FlyingScimitar,
    Zakarumite,
    Faithful,
    Zealot,
    Sexton,
    Cantor,
    Heirophant,
    Heirophant2,
    Mephisto,
    Diablo,
    DeckardCain2,
    DeckardCain3,
    DeckardCain4,
    SwampDweller,
    BogCreature,
    SlimePrince,
    Summoner,
    Tyrael,
    Asheara,
    Hratli,
    Alkor,
    Ormus,
    Izual,
    Halbu,
    WaterWatcherLimb,
    RiverStalkerLimb,
    StygianWatcherLimb,
    WaterWatcherHead,
    RiverStalkerHead,
    StygianWatcherHead,
    Meshif2,
    DeckardCain5,
    Navi,
    BloodRaven,
    Bug,
    Scorpion,
    RogueScout,
    Rogue2,
    Rogue3,
    GargoyleTrap,
    ReturnedMage,
    BoneMage,
    BurningDeadMage,
    HorrorMage,
    RatManShaman,
    FetishShaman,
    FlayerShaman,
    SoulKillerShaman,
    StygianDollShaman,
    Larva,
    SandMaggotQueen,
    RockWormQueen,
    DevourerQueen,
    GiantLampreyQueen,
    WorldKillerQueen,
    ClayGolem,
    BloodGolem,
    IronGolem,
    FireGolem,
    Familiar,
    Act3Male,
    NightMarauder,
    Act3Female,
    Natalya,
    FleshSpawner,
    StygianHag,
    Grotesque,
    FleshBeast,
    StygianDog,
    GrotesqueWyrm,
    Groper,
    Strangler,
    StormCaster,
    Corpulent,
    CorpseSpitter,
    MawFiend,
    DoomKnight,
    AbyssKnight,
    OblivionKnight,
    QuillBear,
    SpikeGiant,
    ThornBrute,
    RazorBeast,
    GiantUrchin,
    Snake,
    Parrot,
    Fish,
    EvilHole,
    EvilHole2,
    EvilHole3,
    EvilHole4,
    EvilHole5,
    FireboltTrap,
    HorzMissileTrap,
    VertMissileTrap,
    PoisonCloudTrap,
    LightningTrap,
    Kaelan,
    InvisoSpawner,
    DiabloClone,
    SuckerNest,
    FeederNest,
    BloodHookNest,
    BloodWingNest,
    Guard,
    MiniSpider,
    BonePrison,
    BonePrison2,
    BonePrison3,
    BonePrison4,
    BoneWall,
    CouncilMember,
    CouncilMember2,
    CouncilMember3,
    Turret,
    Turret2,
    Turret3,
    Hydra,
    Hydra2,
    Hydra3,
    MeleeTrap,
    SevenTombs,
    Decoy,
    Valkyrie,
    Act2Guard3,
    IronWolf,
    Balrog,
    PitLord,
    VenomLord,
    NecroSkeleton,
    NecroMage,
    Griswold,
    CompellingOrbNpc,
    Tyrael2,
    DarkWanderer,
    NovaTrap,
    SpiritMummy,
    LightningSpire,
    FireTower,
    Slinger,
    SpearCat,
    NightSlinger,
    HellSlinger,
    Act2Guard4,
    Act2Guard5,
    ReturnedMage2,
    BoneMage2,
    BaalColdMage,
    HorrorMage2,
    ReturnedMage3,
    BoneMage3,
    BurningDeadMage2,
    HorrorMage3,
    ReturnedMage4,
    BoneMage4,
    BurningDeadMage3,
    HorrorMage4,
    HellBovine,
    Window,
    Window2,
    SpearCat2,
    NightSlinger2,
    RatMan2,
    Fetish2,
    Flayer2,
    SoulKiller2,
    StygianDoll2,
    MephistoSpirit,
    TheSmith,
    TrappedSoul,
    TrappedSoul2,
    Jamella,
    Izual2,
    RatMan3,
    Malachai,
    Hephasto,
    WakeOfDestruction,
    ChargedBoltSentry,
    LightningSentry,
    BladeCreeper,
    InvisiblePet,
    InfernoSentry,
    DeathSentry,
    ShadowWarrior,
    ShadowMaster,
    DruidHawk,
    DruidSpiritWolf,
    DruidFenris,
    SpiritOfBarbs,
    HeartOfWolverine,
    OakSage,
    DruidPlaguePoppy,
    DruidCycleOfLife,
    VineCreature,
    DruidBear,
    Eagle,
    Wolf,
    Bear,
    BarricadeDoor,
    BarricadeDoor2,
    PrisonDoor,
    BarricadeTower,
    RotWalker,
    ReanimatedHorde,
    ProwlingDead,
    UnholyCorpse,
    DefiledWarrior,
    SiegeBeast,
    CrushBiest,
    BloodBringer,
    GoreBearer,
    DeamonSteed,
    SnowYeti,
    SnowYeti2,
    SnowYeti3,
    SnowYeti4,
    WolfRider,
    WolfRider2,
    WolfRider3,
    MinionExp,
    SlayerExp,
    IceBoar,
    FireBoar,
    HellSpawn,
    IceSpawn,
    GreaterHellSpawn,
    GreaterIceSpawn,
    FanaticMinion,
    BerserkSlayer,
    ConsumedIceBoar,
    ConsumedFireBoar,
    FrenziedHellSpawn,
    FrenziedIceSpawn,
    InsaneHellSpawn,
    InsaneIceSpawn,
    SuccubusExp,
    VileTemptress,
    StygianHarlot,
    HellTemptress,
    BloodTemptress,
    Dominus,
    VileWitch,
    StygianFury,
    BloodWitch,
    HellWitch,
    OverSeer,
    Lasher,
    OverLord,
    BloodBoss,
    HellWhip,
    MinionSpawner,
    MinionSlayerSpawner,
    MinionBoarSpawner,
    MinionBoarSpawner2,
    MinionSpawnSpawner,
    MinionBoarSpawner3,
    MinionBoarSpawner4,
    MinionSpawnSpawner2,
    Imp,
    Imp2,
    Imp3,
    Imp4,
    Imp5,
    CatapultS,
    CatapultE,
    CatapultSiege,
    CatapultW,
    FrozenHorror,
    FrozenHorror2,
    FrozenHorror3,
    FrozenHorror4,
    FrozenHorror5,
    BloodLord2,
    BloodLord3,
    BloodLord4,
    BloodLord5,
    BloodLord6,
    Larzuk,
    Drehya,
    Malah,
    NihlathakTown,
    QualKehk,
    CatapultSpotterS,
    CatapultSpotterE,
    CatapultSpotterSiege,
    CatapultSpotterW,
    DeckardCain6,
    Tyrael3,
    Act5Combatant,
    Act5Combatant2,
    BarricadeWallRight,
    BarricadeWallLeft,
    Nihlathak,
    Drehya2,
    EvilHut,
    DeathMauler,
    DeathMauler2,
    DeathMauler3,
    DeathMauler4,
    DeathMauler5,
    Pow,
    Act5Townguard,
    Act5Townguard2,
    AncientStatue,
    AncientStatueNpc2,
    AncientStatueNpc3,
    Talic,
    Madawc,
    Korlic,
    BaalThrone,
    Baal,
    BaalTaunt,
    PutridDefiler,
    PutridDefiler2,
    PutridDefiler3,
    PutridDefiler4,
    PutridDefiler5,
    PainWorm,
    PainWorm2,
    PainWorm3,
    PainWorm4,
    PainWorm5,
    Bunny,
    CouncilMemberBall,
    VenomLord2,
    BaalCrabToStairs,
    Act5Hireling1Hand,
    Act5Hireling2Hand,
    BaalTentacle,
    BaalTentacle2,
    BaalTentacle3,
    BaalTentacle4,
    BaalTentacle5,
    InjuredBarbarian,
    InjuredBarbarian2,
    InjuredBarbarian3,
    BaalCrabClone,
    BaalsMinion,
    BaalsMinion2,
    BaalsMinion3,
    WorldstoneEffect,
    BurningDeadArcher2,
    BoneArcher2,
    BurningDeadArcher3,
    ReturnedArcher2,
    HorrorArcher2,
    Afflicted2,
    Tainted2,
    Misshapen2,
    Disfigured2,
    Damned2,
    MoonClan2,
    NightClan2,
    HellClan2,
    BloodClan2,
    DeathClan2,
    FoulCrow2,
    BloodHawk2,
    BlackRaptor2,
    CloudStalker2,
    ClawViper2,
    PitViper2,
    Salamander2,
    TombViper2,
    SerpentMagus2,
    Marauder2,
    Infidel2,
    SandRaider2,
    Invader2,
    Assailant2,
    DeathMauler6,
    QuillRat2,
    SpikeFiend2,
    RazorSpine2,
    CarrionBird2,
    ThornedHulk2,
    Slinger2,
    Slinger3,
    Slinger4,
    VileArcher2,
    DarkArcher2,
    VileLancer2,
    DarkLancer2,
    BlackLancer2,
    Blunderbore2,
    Mauler2,
    ReturnedMage5,
    BurningDeadMage4,
    ReturnedMage6,
    HorrorMage5,
    BoneMage5,
    HorrorMage6,
    HorrorMage7,
    Huntress2,
    SaberCat2,
    CaveLeaper2,
    TombCreeper2,
    Ghost2,
    Wraith2,
    Specter2,
    SuccubusExp2,
    HellTemptress2,
    Dominus2,
    HellWitch2,
    VileWitch2,
    Gloam2,
    BlackSoul2,
    BurningSoul2,
    Carver2,
    Devilkin2,
    DarkOne2,
    CarverShaman2,
    DevilkinShaman2,
    DarkShaman2,
    BoneWarrior2,
    Returned2,
    Gloombat2,
    Fiend2,
    BloodLord7,
    BloodLord8,
    Scarab2,
    SteelWeevil2,
    Flayer3,
    StygianDoll3,
    SoulKiller3,
    Flayer4,
    StygianDoll4,
    SoulKiller4,
    FlayerShaman2,
    StygianDollShaman2,
    SoulKillerShaman2,
    TempleGuard2,
    TempleGuard3,
    Guardian2,
    Unraveler2,
    HoradrimAncient2,
    HoradrimAncient3,
    Zealot2,
    Zealot3,
    Heirophant3,
    Heirophant4,
    Grotesque2,
    FleshSpawner2,
    GrotesqueWyrm2,
    FleshBeast2,
    WorldKiller2,
    WorldKillerYoung2,
    WorldKillerEgg2,
    SlayerExp2,
    HellSpawn2,
    GreaterHellSpawn2,
    Arach2,
    Balrog2,
    PitLord2,
    Imp6,
    Imp7,
    UndeadStygianDoll2,
    UndeadSoulKiller2,
    Strangler2,
    StormCaster2,
    MawFiend2,
    BloodLord9,
    GhoulLord2,
    DarkLord2,
    UnholyCorpse2,
    DoomKnight2,
    DoomKnight3,
    OblivionKnight2,
    OblivionKnight3,
    Cadaver2,
    UberMephisto,
    UberDiablo,
    UberIzual,
    Lilith,
    UberDuriel,
    UberBaal,
    EvilHut2,
    DemonHole,
    PitLord3,
    OblivionKnight4,
    Imp8,
    HellSwarm2,
    WorldKiller3,
    Arach3,
    SteelWeevil3,
    HellTemptress3,
    VileWitch3,
    FleshHunter2,
    DarkArcher3,
    BlackLancer3,
    HellWhip2,
    Returned3,
    HorrorArcher3,
    BurningDeadMage5,
    HorrorMage8,
    BoneMage6,
    HorrorMage9,
    DarkLord3,
    Specter3,
    BurningSoul3,
    Horse,
    CowKing,
    PlagueBearer2,
    Pig,
    Seagull,
    BerserkSlayer2,
    FrenziedHellSpawn2,
    InsaneHellSpawn2,
    WarGoatman,
    WarBighead,
    WarPutridDefiler,
    Colossal1,
    Colossal2,
    Colossal3,
    ColBarbWhirl,
    ColBarbThrow,
    ColBarbFrenzy,
    #[default]
    Unknown,
    NpcNotApplicable,
}

fn get_type(txt_file_no: &NPC) -> NPCType {
    match txt_file_no {
        // towns folk
        NPC::DeckardCain => NPCType::Town,
        NPC::Charsi => NPCType::Town,
        NPC::Gheed => NPCType::Town,
        NPC::Kashya => NPCType::Town,
        NPC::Warriv => NPCType::Town,
        NPC::Akara => NPCType::Town,
        // Act 2 NPC::
        NPC::DeckardCain2 => NPCType::Town,
        NPC::Meshif => NPCType::Town,
        NPC::Warriv2 => NPCType::Town,
        NPC::Elzix => NPCType::Town,
        NPC::Greiz => NPCType::Town,
        NPC::Drognan => NPCType::Town,
        NPC::Fara => NPCType::Town,
        NPC::Lysander => NPCType::Town,
        NPC::Atma => NPCType::Town,
        NPC::Geglash => NPCType::Town,
        NPC::Kaelan => NPCType::Town,
        NPC::Jerhyn => NPCType::Town,
        // Act 3 NPC::
        NPC::DeckardCain3 => NPCType::Town,
        NPC::Meshif2 => NPCType::Town,
        NPC::Ormus => NPCType::Town,
        NPC::Asheara => NPCType::Town,
        NPC::Alkor => NPCType::Town,
        NPC::Hratli => NPCType::Town,
        NPC::Natalya => NPCType::Town,
        // Act 4 NPC::
        NPC::DeckardCain4 => NPCType::Town,
        NPC::Tyrael => NPCType::Town,
        NPC::Tyrael2 => NPCType::Town,
        NPC::Tyrael3 => NPCType::Town,
        NPC::Halbu => NPCType::Town,
        NPC::Jamella => NPCType::Town,
        // Act 5 NPC::
        NPC::DeckardCain5 => NPCType::Town,
        NPC::DeckardCain6 => NPCType::Town,
        NPC::Drehya => NPCType::Town,
        NPC::Drehya2 => NPCType::Town,
        NPC::QualKehk => NPCType::Town,
        NPC::Malah => NPCType::Town,
        NPC::Larzuk => NPCType::Town,
        NPC::NihlathakTown => NPCType::Town,

        NPC::Navi => NPCType::Town,     // Flavie - the most useful NPC in the game
        NPC::Malachai => NPCType::Town, // Hadriel
        NPC::Izual2 => NPCType::Town,   // Izual's spirit after quest

        // bosses
        NPC::Griswold => NPCType::Boss,
        NPC::BloodRaven => NPCType::Boss,
        NPC::Andariel => NPCType::Boss,
        NPC::Duriel => NPCType::Boss,
        NPC::Radament => NPCType::Boss,
        NPC::Summoner => NPCType::Boss,
        NPC::Izual => NPCType::Boss,
        NPC::Mephisto => NPCType::Boss,
        NPC::Diablo => NPCType::Boss,
        NPC::Nihlathak => NPCType::Boss,
        NPC::Baal => NPCType::Boss,
        NPC::DiabloClone => NPCType::Boss,
        NPC::UberMephisto => NPCType::Boss,
        NPC::UberDiablo => NPCType::Boss,
        NPC::UberIzual => NPCType::Boss,
        NPC::Lilith => NPCType::Boss,
        NPC::UberDuriel => NPCType::Boss,
        NPC::UberBaal => NPCType::Boss,
        NPC::Talic => NPCType::Boss,
        NPC::Madawc => NPCType::Boss,
        NPC::Korlic => NPCType::Boss,

        // player pets
        NPC::Rogue2 => NPCType::Pet,
        NPC::Guard => NPCType::Pet,
        NPC::IronWolf => NPCType::Pet,
        NPC::Act5Hireling1Hand => NPCType::Pet,
        NPC::Act5Hireling2Hand => NPCType::Pet,
        NPC::ClayGolem => NPCType::Pet,
        NPC::BloodGolem => NPCType::Pet,
        NPC::IronGolem => NPCType::Pet,
        NPC::FireGolem => NPCType::Pet,
        NPC::NecroSkeleton => NPCType::Pet,
        NPC::NecroMage => NPCType::Pet,
        NPC::ShadowWarrior => NPCType::Pet,
        NPC::ShadowMaster => NPCType::Pet,
        NPC::DruidHawk => NPCType::Pet,
        NPC::DruidSpiritWolf => NPCType::Pet,
        NPC::DruidFenris => NPCType::Pet,
        NPC::HeartOfWolverine => NPCType::Pet,
        NPC::OakSage => NPCType::Pet,
        NPC::DruidBear => NPCType::Pet,
        NPC::Valkyrie => NPCType::Pet,
        NPC::Hydra => NPCType::Pet,
        NPC::Hydra2 => NPCType::Pet,
        NPC::Hydra3 => NPCType::Pet,

        // ignore
        NPC::Chicken => NPCType::Dummy,
        NPC::Rat => NPCType::Dummy,
        NPC::Rogue => NPCType::Dummy,
        NPC::HellMeteor => NPCType::Dummy,
        NPC::Bird => NPCType::Dummy,
        NPC::Bird2 => NPCType::Dummy,
        NPC::Bat => NPCType::Dummy,
        NPC::Act2Male => NPCType::Dummy,
        NPC::Act2Female => NPCType::Dummy,
        NPC::Act2Child => NPCType::Dummy,
        NPC::Cow => NPCType::Dummy,
        NPC::Camel => NPCType::Dummy,
        NPC::Act2Guard => NPCType::Dummy,
        NPC::Act2Vendor => NPCType::Dummy,
        NPC::Act2Vendor2 => NPCType::Dummy,
        NPC::Maggot => NPCType::Dummy,
        NPC::Bug => NPCType::Dummy,
        NPC::Scorpion => NPCType::Dummy,
        NPC::Rogue3 => NPCType::Dummy,
        NPC::Larva => NPCType::Dummy,
        NPC::Familiar => NPCType::Dummy,
        NPC::Act3Male => NPCType::Dummy,
        NPC::Act3Female => NPCType::Dummy,
        NPC::Snake => NPCType::Dummy,
        NPC::Parrot => NPCType::Dummy,
        NPC::Fish => NPCType::Dummy,
        NPC::EvilHole => NPCType::Dummy,
        NPC::EvilHole2 => NPCType::Dummy,
        NPC::EvilHole3 => NPCType::Dummy,
        NPC::EvilHole4 => NPCType::Dummy,
        NPC::EvilHole5 => NPCType::Dummy,
        NPC::FireboltTrap => NPCType::Dummy,
        NPC::HorzMissileTrap => NPCType::Dummy,
        NPC::VertMissileTrap => NPCType::Dummy,
        NPC::PoisonCloudTrap => NPCType::Dummy,
        NPC::LightningTrap => NPCType::Dummy,
        NPC::InvisoSpawner => NPCType::Dummy,
        NPC::MiniSpider => NPCType::Dummy,
        NPC::BoneWall => NPCType::Dummy,
        NPC::SevenTombs => NPCType::Dummy,
        NPC::Decoy => NPCType::Dummy,
        NPC::CompellingOrbNpc => NPCType::Dummy,
        NPC::SpiritMummy => NPCType::Dummy,
        NPC::Act2Guard4 => NPCType::Dummy,
        NPC::Act2Guard5 => NPCType::Dummy,
        NPC::Window => NPCType::Dummy,
        NPC::Window2 => NPCType::Dummy,
        NPC::MephistoSpirit => NPCType::Dummy,
        NPC::WakeOfDestruction => NPCType::Dummy,
        NPC::ChargedBoltSentry => NPCType::Dummy,
        NPC::LightningSentry => NPCType::Dummy,
        NPC::BladeCreeper => NPCType::Dummy,
        NPC::InvisiblePet => NPCType::Dummy,
        NPC::InfernoSentry => NPCType::Dummy,
        NPC::DeathSentry => NPCType::Dummy,
        NPC::BaalThrone => NPCType::Dummy,
        NPC::InjuredBarbarian => NPCType::Dummy,
        NPC::InjuredBarbarian2 => NPCType::Dummy,
        NPC::InjuredBarbarian3 => NPCType::Dummy,
        NPC::DemonHole => NPCType::Dummy,

        _ => NPCType::Monster,
    }
}

impl From<(&D2RInstance, Unit)> for NPCUnit {
    fn from(data: (&D2RInstance, Unit)) -> Self {
        NPCUnit::new(&data.0, data.1)
    }
}
