use num_derive::FromPrimitive;
use num_traits::FromPrimitive;

use crate::memory::{process::D2RInstance, structs::{SkillList, SkillStrc, SkillTxt}};


#[derive(Debug, Clone, Default)]
pub struct PlayerSkill {
    pub skill: Skill,
    pub quantity: u32,
    pub hard_points: u32,
    pub charges: u32,
}

#[allow(dead_code)]
pub fn get_player_skills(d2rprocess: &D2RInstance, p_skills: u64) -> Vec<PlayerSkill> {
    if p_skills == 0 {
        return vec![];
    };
    let mut all_skills: Vec<PlayerSkill> = vec![];
    let skill_list = d2rprocess.read_mem::<SkillList>(p_skills);
    let mut skill_ptr = skill_list.p_first_skill;
    while skill_ptr > 0 {
        let skill_strc = d2rprocess.read_mem::<SkillStrc>(skill_ptr);
        let skill_txt = d2rprocess.read_mem::<SkillTxt>(skill_strc.p_skill_txt);
        let skill = Skill::from_i16(skill_txt.id).unwrap_or_default();
        let player_skill = PlayerSkill { skill, quantity: skill_strc.quantity, hard_points: skill_strc.hard_points, charges: skill_strc.charges };
        all_skills.push(player_skill);
        skill_ptr = skill_strc.p_next_skill;
    }
    all_skills
}


#[allow(dead_code)]
#[repr(i16)]
#[derive(FromPrimitive, Debug, Clone, PartialEq, Eq, Hash, Copy, Default)]
pub enum Skill {
    Unset = -1,
    Attack = 0,
    Kick,
    Throw,
    Unsummon,
    LeftHandThrow,
    LeftHandSwing,
    MagicArrow,
    FireArrow,
    InnerSight,
    CriticalStrike,
    Jab,
    ColdArrow,
    MultipleShot,
    Dodge,
    PowerStrike,
    PoisonJavelin,
    ExplodingArrow,
    SlowMissiles,
    Avoid,
    Impale,
    LightningBolt,
    IceArrow,
    GuidedArrow,
    Penetrate,
    ChargedStrike,
    PlagueJavelin,
    Strafe,
    ImmolationArrow,
    Decoy,
    Evade,
    Fend,
    FreezingArrow,
    Valkyrie,
    Pierce,
    LightningStrike,
    LightningFury,
    FireBolt,
    Warmth,
    ChargedBolt,
    IceBolt,
    FrozenArmor,
    Inferno,
    StaticField,
    Telekinesis,
    FrostNova,
    IceBlast,
    Blaze,
    FireBall,
    Nova,
    Lightning,
    ShiverArmor,
    FireWall,
    Enchant,
    ChainLightning,
    Teleport,
    GlacialSpike,
    Meteor,
    ThunderStorm,
    EnergyShield,
    Blizzard,
    ChillingArmor,
    FireMastery,
    Hydra,
    LightningMastery,
    FrozenOrb,
    ColdMastery,
    AmplifyDamage,
    Teeth,
    BoneArmor,
    SkeletonMastery,
    RaiseSkeleton,
    DimVision,
    Weaken,
    PoisonDagger,
    CorpseExplosion,
    ClayGolem,
    IronMaiden,
    Terror,
    BoneWall,
    GolemMastery,
    RaiseSkeletalMage,
    Confuse,
    LifeTap,
    PoisonExplosion,
    BoneSpear,
    BloodGolem,
    Attract,
    Decrepify,
    BonePrison,
    SummonResist,
    IronGolem,
    LowerResist,
    PoisonNova,
    BoneSpirit,
    FireGolem,
    Revive,
    Sacrifice,
    Smite,
    Might,
    Prayer,
    ResistFire,
    HolyBolt,
    HolyFire,
    Thorns,
    Defiance,
    ResistCold,
    Zeal,
    Charge,
    BlessedAim,
    Cleansing,
    ResistLightning,
    Vengeance,
    BlessedHammer,
    Concentration,
    HolyFreeze,
    Vigor,
    Conversion,
    HolyShield,
    HolyShock,
    Sanctuary,
    Meditation,
    FistOfTheHeavens,
    Fanaticism,
    Conviction,
    Redemption,
    Salvation,
    Bash,
    BladeMastery,
    AxeMastery,
    MaceMastery,
    Howl,
    FindPotion,
    Leap,
    DoubleSwing,
    PolearmMastery,
    ThrowingMastery,
    SpearMastery,
    Taunt,
    Shout,
    Stun,
    DoubleThrow,
    IncreasedStamina,
    FindItem,
    LeapAttack,
    Concentrate,
    IronSkin,
    BattleCry,
    Frenzy,
    IncreasedSpeed,
    BattleOrders,
    GrimWard,
    Whirlwind,
    Berserk,
    NaturalResistance,
    WarCry,
    BattleCommand,
    FireHit,
    UnHolyBolt,
    SkeletonRaise,
    MaggotEgg,
    ShamanFire,
    MagottUp,
    MagottDown,
    MagottLay,
    AndrialSpray,
    Jump,
    SwarmMove,
    Nest,
    QuickStrike,
    VampireFireball,
    VampireFirewall,
    VampireMeteor,
    GargoyleTrap,
    SpiderLay,
    VampireHeal,
    VampireRaise,
    Submerge,
    FetishAura,
    FetishInferno,
    ZakarumHeal,
    Emerge,
    Resurrect,
    Bestow,
    MissileSkill1,
    MonTeleport,
    PrimeLightning,
    PrimeBolt,
    PrimeBlaze,
    PrimeFirewall,
    PrimeSpike,
    PrimeIceNova,
    PrimePoisonball,
    PrimePoisonNova,
    DiabLight,
    DiabCold,
    DiabFire,
    FingerMageSpider,
    FireStorm,
    DiabRun,
    DiabPrison,
    PoisonBallTrap,
    AndyPoisonBolt,
    HireableMissile,
    DesertTurret,
    ArcaneTower,
    MonBlizzard,
    Mosquito,
    CursedBallTrapRight,
    CursedBallTrapLeft,
    MonFrozenArmor,
    MonBoneArmor,
    MonBoneSpirit,
    MonCurseCast,
    HellMeteor,
    RegurgitatorEat,
    MonFrenzy,
    QueenDeath,
    ScrollOfIdentify,
    TomeOfIdentify,
    ScrollOfTownPortal,
    TomeOfTownPortal,
    Raven,
    PoisonCreeper,
    Werewolf,
    Lycanthropy,
    Firestorm,
    OakSage,
    SummonSpiritWolf,
    Werebear,
    MoltenBoulder,
    ArcticBlast,
    CarrionVine,
    FeralRage,
    Maul,
    Fissure,
    CycloneArmor,
    HeartOfWolverine,
    SummonDireWolf,
    Rabies,
    FireClaws,
    Twister,
    SolarCreeper,
    Hunger,
    ShockWave,
    Volcano,
    Tornado,
    SpiritOfBarbs,
    SummonGrizzly,
    Fury,
    Armageddon,
    Hurricane,
    FireBlast,
    ClawMastery,
    PsychicHammer,
    TigerStrike,
    DragonTalon,
    ShockWeb,
    BladeSentinel,
    BurstOfSpeed,
    FistsOfFire,
    DragonClaw,
    ChargedBoltSentry,
    WakeOfFire,
    WeaponBlock,
    CloakOfShadows,
    CobraStrike,
    BladeFury,
    Fade,
    ShadowWarrior,
    ClawsOfThunder,
    DragonTail,
    LightningSentry,
    WakeOfInferno,
    MindBlast,
    BladesOfIce,
    DragonFlight,
    DeathSentry,
    BladeShield,
    Venom,
    ShadowMaster,
    PhoenixStrike,
    WakeOfDestructionSentry,
    ImpInferno,
    ImpFireball,
    BaalTaunt,
    BaalCorpseExplode,
    BaalMonsterSpawn,
    CatapultChargedBall,
    CatapultSpikeBall,
    SuckBlood,
    CryHelp,
    HealingVortex,
    Teleport2,
    SelfResurrect,
    VineAttack,
    OverseerWhip,
    BarbsAura,
    WolverineAura,
    OakSageAura,
    ImpFireMissile,
    Impregnate,
    SiegeBeastStomp,
    MinionSpawner,
    CatapultBlizzard,
    CatapultPlague,
    CatapultMeteor,
    BoltSentry,
    CorpseCycler,
    DeathMaul,
    DefenseCurse,
    BloodMana,
    MonInfernoSentry,
    MonDeathSentry,
    SentryLightning,
    FenrisRage,
    BaalTentacle,
    BaalNova,
    BaalInferno,
    BaalColdMissiles,
    MegademonInferno,
    EvilHutSpawner,
    CountessFirewall,
    ImpBolt,
    HorrorArcticBlast,
    DeathSentryLtng,
    VineCycler,
    BearSmite,
    Resurrect2,
    BloodLordFrenzy,
    BaalTeleport,
    ImpTeleport,
    BaalCloneTeleport,
    ZakarumLightning,
    VampireMissile,
    MephistoMissile,
    DoomKnightMissile,
    RogueMissile,
    HydraMissile,
    NecromageMissile,
    MonBow,
    MonFireArrow,
    MonColdArrow,
    MonExplodingArrow,
    MonFreezingArrow,
    MonPowerStrike,
    SuccubusBolt,
    MephFrostNova,
    MonIceSpear,
    ShamanIce,
    Diablogeddon,
    DeleriumChange,
    NihlathakCorpseExplosion,
    SerpentCharge,
    TrapNova,
    UnHolyBoltEx,
    ShamanFireEx,
    ImpFireMissileEx,
    FixedSiegeBeastStomp,
    #[default]
    Unknown
}

#[allow(dead_code)]
pub fn get_skill_class(class_id: u16) -> String {
    match class_id {
        6..=35 => String::from("Amazon"),
        36..=65 => String::from("Sorceress"),
        66..=95 => String::from("Necromancer"),
        96..=125 => String::from("Paladin"),
        126..=155 => String::from("Barbarian"),
        _ => String::new()
    }
}

#[allow(dead_code)]
#[repr(i16)]
#[derive(FromPrimitive, Debug, Clone, PartialEq, Eq, Hash, Copy)]
pub enum SkillTree {
    AmazonBowAndCrossbow = 0,
    AmazonPassiveAndMagic = 1,
    AmazonJavelinAndSpear = 2,
    SorceressFire = 8,
    SorceressLightning = 9,
    SorceressCold = 10,
    NecromancerCurses = 16,
    NecromancerPoisonAndBone = 17,
    NecromancerSummoning = 18,
    PaladinCombatSkills = 24,
    PaladinOffensiveAuras = 25,
    PaladinDefensiveAuras = 26,
    BarbarianCombatSkills = 32,
    BarbarianMasteries = 33,
    BarbarianWarcries = 34,
    DruidSummoning = 40,
    DruidShapeShifting = 41,
    DruidElemental = 42,
    AssassinTraps = 48,
    AssassinShadowDisciplines = 49,
    AssassinMartialArts = 50,
}